import {test} from "node:test";
import assert from "node:assert/strict";
import {DatabaseSync} from "node:sqlite";
import {readFileSync} from "node:fs";
import {newApplication,newStage,validateApplication,migrateV1,calendarEvents,eventsOn,due,point,isUpcoming} from "../lib/applications";
import {repository} from "../lib/repository";
import {parsePeriod} from "../lib/jobs";
import {columns,moveApplication,columnFor} from '../lib/kanban';
import {parsePublicJobs,publicRowsFromHtml} from '../lib/search';
import {isOwner} from '../lib/access';
test('모집 기간은 시작·마감 두 이벤트, 중간 날짜는 비움',()=>{const a=app();a.recruitment.start=point({date:'2026-08-31',time:'18:00'});a.recruitment.end=point({date:'2026-09-09',time:'18:00'});const events=calendarEvents([a]);assert.equal(events.length,2);assert.equal(eventsOn(events,'2026-09-05').length,0);assert.ok(events.some(e=>e.type==='recruitment_deadline'));assert.equal(a.recruitment.start.date,'2026-08-31')});
test('칸반 이동은 현재 전형만 지정하고 이전 전형 결과를 보존',()=>{const a=app();a.stages[0].status='completed';const c=columns([a]).find(c=>c.name==='AI 역량검사')!;const moved=moveApplication(a,c);assert.equal(columnFor(moved),c.id);assert.equal(moved.stages[0].status,'completed');assert.equal(moved.stages[1].status,'not_started');assert.equal(moved.managementStatus,'active');assert.equal(a.currentStageId,null);assert.throws(()=>moveApplication(a,{id:'archived',name:'종료',kind:'archived'}));const custom=moveApplication(a,{id:'stage:PT 발표',name:'PT 발표',kind:'stage'});assert.equal(custom.stages.at(-1)!.name,'PT 발표');validateApplication(custom)});
test('공개 검색은 모집 필드만 사용하고 게시일·임의 시각을 저장하지 않음',()=>{const candidates=parsePublicJobs([{jobId:'2609020000070',companyNm:'검증 기업',title:'검증 공고',regDate:'20260901',inviteStartDt:'20260902',inviteCloseDt:'20260909'},{jobId:'2609020000071',companyNm:'검증 기업',title:'기간 미공개',regDate:'20260901'}]);assert.equal(candidates[0].start!.date,'2026-09-02');assert.equal(candidates[0].end!.time,null);assert.equal(candidates[1].start,null);assert.equal(candidates[0].sourceKind,'public');assert.deepEqual(parsePublicJobs([{title:'기업 정보만'}]),[]);const payload='a:["$","x",null,{"initialJobs":[{"title":"x]y"}]}]';assert.deepEqual(publicRowsFromHtml('<script>self.__next_f.push('+JSON.stringify([1,payload])+')</script>'),[{title:'x]y'}])});
test('공개 방문자와 다른 계정은 수정 불가',()=>{assert.equal(isOwner(null,'owner'),false);assert.equal(isOwner('other','owner'),false);assert.equal(isOwner('owner',undefined),false);assert.equal(isOwner('owner','owner'),true)});
function app(){const a=newApplication();a.companyName="지역수협";a.postingTitle="신입";return a}
test("필수 두 필드만 등록, 날짜·URL 없음",()=>{const a=app();validateApplication(a);assert.equal(a.postingUrl,null);assert.equal(a.recruitment.start,null);assert.equal(calendarEvents([a]).length,0)});
test("날짜만 마감: KST 당일 유지, 다음날 마감",()=>{const a=app();a.recruitment.end=point({date:"2026-09-07",time:null});assert.equal(due(a,Date.parse("2026-09-07T23:59:59+09:00")).closed,false);assert.equal(due(a,Date.parse("2026-09-08T00:00:00+09:00")).closed,true);assert.equal(a.recruitment.end!.time,null)});
test("독립 시작·마감 및 역전 시간 거부",()=>{const a=app();a.recruitment.start=point({date:"2026-09-07",time:"18:00"});validateApplication(a);a.recruitment.end=point({date:"2026-09-07",time:"17:00"});assert.throws(()=>validateApplication(a));a.recruitment.start=null;validateApplication(a)});
test("서류 완료와 합격 분리, 현재 전형 제외 금지",()=>{const a=app();a.stages[0].status="completed";a.currentStageId=a.stages[2].id;validateApplication(a);assert.equal(a.managementStatus,"interested");assert.equal(a.stages[0].status,"completed");a.stages[2].status="not_applicable";a.stages[2].applicable=false;assert.throws(()=>validateApplication(a))});
test("순서 변경·추가·일정 파생 및 월 경계",()=>{const a=app();a.stages[2].schedule.start=point({date:"2026-09-30",time:"10:00"});a.stages[2].schedule.end=point({date:"2026-10-02",time:null});const id=a.stages[2].id;a.stages.reverse();a.stages=a.stages.map((s,i)=>({...s,order:i}));a.stages.push(newStage("PT면접",6));validateApplication(a);assert.equal(a.stages.find(s=>s.id===id)!.schedule.start!.time,"10:00");assert.equal(eventsOn(calendarEvents([a]),"2026-10-01").length,1);a.stages.find(s=>s.id===id)!.schedule.end!.date="2026-09-30";assert.equal(eventsOn(calendarEvents([a]),"2026-10-01").length,0)});
const legacy={version:1,companies:[{id:"kb",name:"KB국민은행",provider:"kb"}],postings:[{id:"legacy",companyId:"kb",title:"신입행원",url:"https://kbstar.careerlink.kr/jobs/RC1",start:null,end:{date:"2026-09-09",time:"18:00",second:59},kind:"official",source:"official",evidence:"접수기간",checkedAt:"2026-09-07T01:00:00Z",stage:"지원 완료",notes:"기존 메모",saved:true}],scans:[]};
test("v1 이전은 메모·초·ID 보존, 서류만 완료",()=>{const s=migrateV1(legacy),a=s.applications[0];assert.equal(a.id,"legacy");assert.equal(a.notes,"기존 메모");assert.equal(a.recruitment.end!.second,59);assert.equal(a.managementStatus,"active");assert.equal(a.stages[0].status,"completed");assert.ok(a.stages.slice(1).every(x=>x.status==="not_started"&&!x.schedule.start));assert.throws(()=>migrateV1({version:1}))});
test("공식 모집기간 파서 유지",()=>{const r=parsePeriod("2026. 8. 28 ~ 2026. 9. 14 10:00");assert.equal(r?.end.time,"10:00");assert.equal(r?.start.time,null)});
function database(){const sql=new DatabaseSync(":memory:");for(const f of ["0000_regular_xavin.sql","0001_windy_vargas.sql"])sql.exec(readFileSync("drizzle/"+f,"utf8"));let fail=false;const db={prepare(query:string){let values:unknown[]=[];return{bind(...v:unknown[]){values=v;return this},async first(){return sql.prepare(query).get(...values as never[])??null},async run(){const r=sql.prepare(query).run(...values as never[]);return{meta:{changes:Number(r.changes)}}}}},async batch(statements:{run:()=>Promise<unknown>}[]){sql.exec("BEGIN");try{const results=[];for(let i=0;i<statements.length;i++){if(fail&&i===1)throw new Error("injected write failure");results.push(await statements[i].run())}sql.exec("COMMIT");return results}catch(e){sql.exec("ROLLBACK");throw e}}};return{sql,db:db as unknown as D1Database,setFail(v:boolean){fail=v}}}
test("실제 SQLite 트랜잭션: 백업 후 이전·재조회·실패 원복·충돌 거부",async()=>{const {sql,db,setFail}=database();const raw=JSON.stringify(legacy);sql.prepare("INSERT INTO app_state VALUES (1,?,?)").run(raw,"now");const r=repository(db);const s=await r.read();assert.equal(s.applications.length,1);assert.equal(sql.prepare("SELECT payload FROM job_backups WHERE id='legacy-v1'").get()!.payload,raw);assert.equal(sql.prepare("SELECT payload FROM app_state").get()!.payload,raw);const updated=await r.update(0,x=>{x.applications[0].notes="수정";return x});assert.equal((await repository(db).read()).applications[0].notes,"수정");await assert.rejects(()=>r.update(0,x=>x));setFail(true);await assert.rejects(()=>r.update(updated.revision,x=>{x.applications=[];return x}));assert.equal((await r.read()).applications.length,1);assert.equal((await r.read()).revision,1);sql.close()});
test("손상된 v1 JSON은 초기화하지 않음",async()=>{const {sql,db}=database();sql.prepare("INSERT INTO app_state VALUES (1,?,?)").run("{broken","now");await assert.rejects(()=>repository(db).read());assert.equal(sql.prepare("SELECT count(*) n FROM job_state_v2").get()!.n,0);assert.equal(sql.prepare("SELECT payload FROM app_state").get()!.payload,"{broken");sql.close()});
test("스냅샷 복구 전 현재 상태도 보존",async()=>{const {sql,db}=database();const r=repository(db);await r.read();await r.update(0,s=>{s.applications=[app()];return s});await r.update(1,s=>{s.applications[0].notes="변경";return s});const row=sql.prepare("SELECT id FROM job_backups WHERE json_extract(payload,'$.revision')=1").get()!;const saved=await r.backup(String(row.id));const restored=await r.update(2,s=>({...s,applications:saved.applications}));assert.equal(restored.revision,3);assert.equal(restored.applications[0].notes,"");assert.ok(sql.prepare("SELECT id FROM job_backups WHERE json_extract(payload,'$.applications[0].notes')='변경'").get());sql.close()});
test("오늘 이미 지난 시각 제외, 시각 미공개는 유지",()=>{const a=app();a.recruitment.end=point({date:"2026-09-08",time:"09:00"});const now=Date.parse("2026-09-08T10:00:00+09:00");assert.equal(isUpcoming(calendarEvents([a])[0],now),false);a.recruitment.end!.time=null;assert.equal(isUpcoming(calendarEvents([a])[0],now),true)});
