"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import {addDays,eventDate,eventLabels,eventsOn,stageLabels,type Application,type CalendarEvent,type ReminderOffset,type StageKind,type StageStatus} from "@/lib/applications";
import {formatPoint,kstDate} from "@/lib/jobs";

export type QuickView="all"|"today"|"week"|"unsubmitted"|"results"|"undated";
type CalendarProps={events:CalendarEvent[];undatedApplications:Application[];onOpen:(e:CalendarEvent)=>void;onOpenApplication:(a:Application)=>void;onAddDate:(date:string)=>void;onMove:(e:CalendarEvent,targetDate:string)=>void|Promise<void>;onTogglePreparation:(e:CalendarEvent,completed:boolean)=>void|Promise<void>;onStageStatus:(e:CalendarEvent,status:StageStatus)=>void|Promise<void>;onReminder:(e:CalendarEvent,offset:ReminderOffset|null)=>void|Promise<void>;onAcknowledge:(e:CalendarEvent)=>void|Promise<void>;canEdit:boolean;busy:boolean;storageKey?:string;command?:{id:number;quick:QuickView}|null};
type CalendarView="month"|"week"|"list";
type SavedCalendarState={view?:CalendarView;date?:string;company?:string;types?:string[];selected?:string;quick?:QuickView;favoriteOnly?:boolean};
const kindLabels:Record<StageKind,string>={preparation:"준비",document:"서류",aptitude:"AI·인적성",written:"필기",interview:"면접",result:"결과 발표",personal:"개인 준비"};
const quickLabels:Record<QuickView,string>={all:"전체",today:"오늘",week:"이번 주",unsubmitted:"미제출 마감",results:"결과 대기",undated:"일정 미정"};
function readCalendarState(key?:string):SavedCalendarState|null{if(typeof window==="undefined"||!key)return null;try{const raw=window.localStorage.getItem(key);return raw?JSON.parse(raw) as SavedCalendarState:null}catch{return null}}
function reminderFingerprint(event:CalendarEvent){const point=event.schedule.start??event.schedule.end!;return point.date+"T"+(point.time??"date")}
function reminderDue(event:CalendarEvent,today:string){const reminder=event.reminder;if(!reminder||reminder.acknowledgedFor===reminderFingerprint(event)||event.preparationCompleted||['withdrawn','rejected','accepted'].includes(event.managementStatus))return false;if(event.stageStatus&&event.type!=="result_expected"&&['completed','passed','failed','not_applicable'].includes(event.stageStatus))return false;if(event.stageStatus&&event.type==="result_expected"&&['passed','failed','not_applicable'].includes(event.stageStatus))return false;return addDays(eventDate(event),-reminder.offsetDays)<=today&&today<=eventDate(event)}
function timeConflictCount(events:CalendarEvent[]){let count=0;for(let i=0;i<events.length;i++)for(let j=i+1;j<events.length;j++){const a=events[i].schedule,b=events[j].schedule;if(a.start?.time&&a.end?.time&&b.start?.time&&b.end?.time&&a.start.date===b.start.date&&a.start.time<b.end.time&&b.start.time<a.end.time)count++}return count}

export function Calendar({events,undatedApplications,onOpen,onOpenApplication,onAddDate,onMove,onTogglePreparation,onStageStatus,onReminder,onAcknowledge,canEdit,busy,storageKey,command}:CalendarProps){
 const saved=readCalendarState(storageKey),today=kstDate(),allTypes=Object.keys(eventLabels),initialTypes=Array.isArray(saved?.types)?saved.types.filter(type=>allTypes.includes(type)):allTypes;
 if(initialTypes.length===allTypes.length-1&&!initialTypes.includes("preparation"))initialTypes.push("preparation");
 const [view,setView]=useState<CalendarView>(saved?.view??"month"),[date,setDate]=useState(saved?.date??today),[company,setCompany]=useState(saved?.company??""),[types,setTypes]=useState<string[]>(initialTypes),[selected,setSelected]=useState(saved?.selected??saved?.date??today),[quick,setQuick]=useState<QuickView>(saved?.quick??"all"),[favoriteOnly,setFavoriteOnly]=useState(!!saved?.favoriteOnly),[includePersonal,setIncludePersonal]=useState(true),[includeUrl,setIncludeUrl]=useState(true),[draggingId,setDraggingId]=useState<string|null>(null),[dropDate,setDropDate]=useState<string|null>(null);
 const suppressClick=useRef(false);
 useEffect(()=>{if(command)selectQuick(command.quick)},[command]);
 useEffect(()=>{if(!storageKey)return;try{window.localStorage.setItem(storageKey,JSON.stringify({view,date,company,types,selected,quick,favoriteOnly}))}catch{/* optional preference storage */}},[storageKey,view,date,company,types,selected,quick,favoriteOnly]);
 const filtered=useMemo(()=>events.filter(event=>{if(company&&event.companyName!==company||favoriteOnly&&!event.favorite||!types.includes(event.type))return false;if(quick==="today")return eventDate(event)===today;if(quick==="week")return eventDate(event)>=today&&eventDate(event)<=addDays(today,6);if(quick==="unsubmitted")return event.type==="recruitment_deadline"&&!event.documentSubmitted&&eventDate(event)>=today;if(quick==="results")return event.type==="result_expected"&&!['passed','failed'].includes(event.stageStatus??"");if(quick==="undated")return false;return true}),[events,company,favoriteOnly,types,quick,today]);
 const first=date.slice(0,7)+"-01",day=new Date(first+"T12:00:00Z").getUTCDay(),start=view==="month"?addDays(first,-day):addDays(date,-new Date(date+"T12:00:00Z").getUTCDay()),days=Array.from({length:view==="month"?42:7},(_,i)=>addDays(start,i)),monthEnd=new Date(Date.UTC(Number(first.slice(0,4)),Number(first.slice(5,7)),0,12)).toISOString().slice(0,10);
 const list=filtered.filter(event=>eventDate(event)<=monthEnd&&(event.schedule.end?.date??eventDate(event))>=first),selectedEvents=eventsOn(filtered,selected),activeReminders=events.filter(event=>reminderDue(event,today));
 const visibleUndated=undatedApplications.filter(application=>!favoriteOnly||application.favorite),selectedAttendance=selectedEvents.filter(event=>['exam','interview'].includes(event.type)),conflicts=timeConflictCount(selectedAttendance);
 function move(n:number){let next:string;if(view==="week")next=addDays(date,7*n);else{const value=new Date(first+"T12:00:00Z");value.setUTCMonth(value.getUTCMonth()+n);next=value.toISOString().slice(0,10)}setDate(next);setSelected(next)}
 function selectQuick(value:QuickView){setQuick(value);if(value==="today"||value==="week"){setDate(today);setSelected(today)}}
 function beginDrag(event:React.DragEvent<HTMLButtonElement>,item:CalendarEvent){if(!canEdit||busy)return;event.dataTransfer.setData("text/plain",item.id);event.dataTransfer.effectAllowed="move";setDraggingId(item.id);setDropDate(null)}
 function dropOn(dateValue:string){if(!draggingId)return;const item=events.find(event=>event.id===draggingId);setDraggingId(null);setDropDate(null);if(!item||eventDate(item)===dateValue)return;suppressClick.current=true;window.setTimeout(()=>{suppressClick.current=false},0);void onMove(item,dateValue)}
 function statusBadge(event:CalendarEvent){if(event.preparationCompleted)return <span className="status-badge status-completed">✓ 완료</span>;if(!event.stageStatus)return null;return <span className={`status-badge status-${event.stageStatus}`}>{stageLabels[event.stageStatus]}</span>}
 function eventActions(event:CalendarEvent){return <div className="event-actions"><button type="button" onClick={()=>onOpen(event)}>공고 열기</button>{event.preparationId&&<button type="button" disabled={busy} onClick={()=>void onTogglePreparation(event,!event.preparationCompleted)}>{event.preparationCompleted?"완료 취소":"준비 완료"}</button>}{event.stageId&&!['result_expected','result_confirmed'].includes(event.type)&&<label><span className="sr-only">전형 상태</span><select disabled={busy} value={event.stageStatus??"not_started"} onChange={e=>void onStageStatus(event,e.target.value as StageStatus)}>{Object.entries(stageLabels).filter(([key])=>key!=="not_applicable").map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}<label><span className="sr-only">리마인더</span><select disabled={busy} value={event.reminder?.offsetDays??""} onChange={e=>void onReminder(event,e.target.value===""?null:Number(e.target.value) as ReminderOffset)}><option value="">알림 없음</option><option value="0">당일</option><option value="1">전날</option><option value="3">3일 전</option></select></label>{reminderDue(event,today)&&<button type="button" className="reminder-ack" disabled={busy} onClick={()=>void onAcknowledge(event)}>알림 확인</button>}</div>}
 function chip(event:CalendarEvent,compact=false){const point=event.schedule.start??event.schedule.end!,kind=eventLabels[event.type],showKind=event.title!==kind,urgent=event.type==="recruitment_deadline"&&eventDate(event)>=today&&eventDate(event)<=addDays(today,3);return <div key={event.id} className={`event-item kind-${event.kind}${event.preparationCompleted?" is-complete":""}`}><button type="button" draggable={canEdit&&!busy} className={`event-chip kind-${event.kind}${compact?" compact":""}${draggingId===event.id?" dragging":""}`} title={event.companyName+" · "+event.title+" · "+formatPoint(point)} onDragStart={e=>beginDrag(e,event)} onDragEnd={()=>{setDraggingId(null);setDropDate(null)}} onClick={e=>{if(suppressClick.current){e.preventDefault();suppressClick.current=false;return}onOpen(event)}}><span className="event-dot"/><strong>{event.favorite&&<span className="favorite-mark" aria-label="즐겨찾기">★</span>}{compact?event.companyName:event.companyName+" · "+event.title}</strong>{compact&&<span className="event-kind">{kind}</span>}<time>{compact?point.time??"":formatPoint(point)}{!compact&&event.schedule.end&&event.schedule.start?" ~ "+formatPoint(event.schedule.end):""}</time>{!compact&&<span className="event-meta">{showKind&&<small>{kind}{event.schedule.tentative?" · 예정":""}</small>}{statusBadge(event)}{urgent&&<span className="urgency-badge">◷ 마감 임박</span>}</span>}</button>{canEdit&&!compact&&<details className="event-date-editor" onClick={e=>e.stopPropagation()}><summary aria-label={event.title+" 날짜 변경"}>날짜 변경</summary><div><label>변경할 날짜<input type="date" defaultValue={eventDate(event)} disabled={busy} onChange={e=>{if(e.target.value){void onMove(event,e.target.value);e.currentTarget.closest("details")?.removeAttribute("open")}}}/></label></div></details>}{!compact&&canEdit&&eventActions(event)}</div>}
 const groups=[{key:"official",title:"공식 전형 일정",items:selectedEvents.filter(event=>!['personal','preparation','result_expected','result_confirmed'].includes(event.type))},{key:"personal",title:"개인 준비 항목",items:selectedEvents.filter(event=>['personal','preparation'].includes(event.type))},{key:"result",title:"확인할 결과",items:selectedEvents.filter(event=>['result_expected','result_confirmed'].includes(event.type))}];
 const exportParams=new URLSearchParams({from:first,to:monthEnd,includePersonal:String(includePersonal),includeUrl:String(includeUrl)});if(company)exportParams.set("company",company);
 return <section className="calendar"><div className="calendar-toolbar"><h2>{date.slice(0,4)}년 {Number(date.slice(5,7))}월{view==="week"&&<small> · {start.slice(5)}부터 7일</small>}</h2><div className="calendar-controls"><button onClick={()=>{setDate(today);setSelected(today)}}>오늘</button><button onClick={()=>move(-1)} aria-label="이전 기간">‹</button><button onClick={()=>move(1)} aria-label="다음 기간">›</button><div className="tabs">{[["month","월간"],["week","주간"],["list","목록"]].map(([value,label])=><button key={value} aria-pressed={view===value} className={view===value?"active":""} onClick={()=>setView(value as CalendarView)}>{label}</button>)}</div><details className="calendar-more"><summary>더보기</summary><div><label className="check"><input type="checkbox" checked={includePersonal} onChange={e=>setIncludePersonal(e.target.checked)}/>개인 준비 일정 포함</label><label className="check"><input type="checkbox" checked={includeUrl} onChange={e=>setIncludeUrl(e.target.checked)}/>공고 URL 포함</label><a href={`/api/calendar-export?${exportParams}`} download>현재 달 .ics 내보내기</a><small>외부 캘린더에 가져오는 파일이며 자동 동기화는 아닙니다. 반복 가져오면 중복될 수 있습니다.</small></div></details></div></div>
  <div className="quick-filters" aria-label="빠른 일정 보기">{(Object.keys(quickLabels) as QuickView[]).map(value=><button type="button" aria-pressed={quick===value} className={quick===value?"active":""} key={value} onClick={()=>selectQuick(value)}>{quickLabels[value]}</button>)}<button type="button" aria-pressed={favoriteOnly} className={favoriteOnly?"active favorite":"favorite"} onClick={()=>setFavoriteOnly(value=>!value)}>★ 즐겨찾기</button></div>
  <div className="calendar-filters"><select aria-label="기업 필터" value={company} onChange={e=>setCompany(e.target.value)}><option value="">전체 기업</option>{[...new Set(events.map(event=>event.companyName))].map(value=><option key={value}>{value}</option>)}</select><details className="filter-popover"><summary>{types.length===allTypes.length?"모든 일정":types.length?`일정 종류 ${types.length}개`:"일정 종류 없음"}⌄</summary><div><button onClick={()=>setTypes(types.length?[]:allTypes)}>{types.length?"전체 해제":"전체 선택"}</button>{Object.entries(eventLabels).map(([value,label])=><label key={value} className="check"><input type="checkbox" checked={types.includes(value)} onChange={e=>setTypes(e.target.checked?[...types,value]:types.filter(type=>type!==value))}/>{label}</label>)}</div></details><input aria-label="기준 날짜" type="date" value={date} onChange={e=>{if(e.target.value){setDate(e.target.value);setSelected(e.target.value)}}}/><div className="calendar-legend" aria-label="전형 색상 범례">{(Object.keys(kindLabels) as StageKind[]).map(kind=><span className={`kind-${kind}`} key={kind}><i/>{kindLabels[kind]}</span>)}</div></div>
  {activeReminders.length>0&&<aside className="reminder-panel" aria-label="확인할 앱 내부 알림"><div><strong>확인할 알림 {activeReminders.length}개</strong><span>취준캘린더를 열었을 때 표시되는 알림입니다.</span></div><div>{activeReminders.slice(0,5).map(event=><button type="button" key={event.id} onClick={()=>onOpen(event)}><span>{event.companyName} · {event.title}</span><time>{eventDate(event).slice(5)}</time></button>)}</div></aside>}
  {visibleUndated.length>0&&<aside className={`undated-panel${quick==="undated"?" highlighted":""}`} aria-label="일정 미정 공고"><div><strong>일정 미정 공고 {visibleUndated.length}개</strong><span>날짜를 입력하지 않은 공고도 여기서 확인할 수 있습니다.</span></div><div className="undated-list">{visibleUndated.map(application=><button key={application.id} type="button" onClick={()=>onOpenApplication(application)}><strong>{application.favorite&&"★ "}{application.companyName}</strong><span>{application.postingTitle}</span></button>)}</div></aside>}
  {view==="list"?<div className="agenda">{list.length?list.map(event=>chip(event)):<div className="empty-day"><p className="empty">이 조건에 표시할 일정이 없습니다.</p>{canEdit&&<button type="button" onClick={()=>onAddDate(selected)}>이 날짜에 일정 추가</button>}</div>}</div>:<><div className={`calendar-grid ${view==="week"?"week-grid":""}`}>{days.map(value=>{const items=eventsOn(filtered,value),attendance=items.filter(event=>['exam','interview'].includes(event.type));return <div className={`day-cell ${value===today?"today ":""}${value===selected?"selected ":""}${value.slice(0,7)!==date.slice(0,7)?"outside ":""}${dropDate===value?"drop-target":""}`} key={value} onDragOver={e=>{if(canEdit&&draggingId){e.preventDefault();setDropDate(value)}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDropDate(null)}} onDrop={e=>{e.preventDefault();dropOn(value)}}><button className="day-number" onClick={()=>setSelected(value)} aria-label={value+" 일정 "+items.length+"개"}><span>{Number(value.slice(8))}</span><small>{["일","월","화","수","목","금","토"][new Date(value+"T12:00:00Z").getUTCDay()]}</small>{items.length>0&&<b>{items.length}</b>}</button>{attendance.length>=2&&<span className="day-load">전형 {attendance.length}</span>}<div className="cell-events">{items.slice(0,view==="month"?3:1000).map(event=>chip(event,view==="month"))}{view==="month"&&items.length>3&&<button className="more" onClick={()=>setSelected(value)}>+{items.length-3}개 더보기</button>}</div>{items.length>0&&<button className="mobile-count" aria-label={value+" 일정 목록"} onClick={()=>setSelected(value)}>{items.length}개</button>}</div>})}</div><div className="day-list"><div className="day-list-heading"><div><h3>{selected.slice(5).replace("-","월 ")}일 <span>{selectedEvents.length}개 일정</span></h3>{selected!==today&&<p>선택한 날짜 · 오늘은 {today.slice(5).replace("-","월 ")}일입니다.</p>}</div>{canEdit&&<button type="button" className="text-button" onClick={()=>onAddDate(selected)}>＋ 이 날짜에 일정 추가</button>}</div>{selectedAttendance.length>=2&&<p className="density-notice">같은 날 전형 {selectedAttendance.length}개{conflicts?` · 시각이 겹치는 일정 ${conflicts}쌍`:" · 시각이 확인된 일정은 겹침 여부를 함께 확인하세요."}</p>}{selectedEvents.length?groups.filter(group=>group.items.length).map(group=><section className="day-group" key={group.key}><h4>{group.title}</h4>{group.items.map(event=>chip(event))}</section>):<div className="empty-day"><p className="hint">등록된 일정이 없습니다. 선택한 공고에 일정을 추가해 보세요.</p>{canEdit&&<button type="button" onClick={()=>onAddDate(selected)}>이 날짜에 일정 추가</button>}</div>}</div></>}
 </section>
}
