"use client";
import {useMemo,useRef,useState} from "react";
import {addDays,eventDate,eventLabels,eventsOn,type Application,type CalendarEvent} from "@/lib/applications";
import {kstDate,formatPoint} from "@/lib/jobs";

type CalendarProps={events:CalendarEvent[];upcoming:CalendarEvent[];undatedApplications:Application[];onOpen:(e:CalendarEvent)=>void;onOpenApplication:(a:Application)=>void;onMove:(e:CalendarEvent,targetDate:string)=>void|Promise<void>;canEdit:boolean;busy:boolean};

export function Calendar({events,upcoming,undatedApplications,onOpen,onOpenApplication,onMove,canEdit,busy}:CalendarProps){
 const [view,setView]=useState("month"),[date,setDate]=useState(kstDate()),[company,setCompany]=useState(""),[types,setTypes]=useState<string[]>(Object.keys(eventLabels)),[selected,setSelected]=useState(kstDate()),[draggingId,setDraggingId]=useState<string|null>(null),[dropDate,setDropDate]=useState<string|null>(null);
 const suppressClick=useRef(false);
 const filtered=useMemo(()=>events.filter(e=>(!company||e.companyName===company)&&types.includes(e.type)),[events,company,types]);
 const first=date.slice(0,7)+"-01",day=new Date(first+"T12:00:00Z").getUTCDay(),start=view==="month"?addDays(first,-day):addDays(date,-new Date(date+"T12:00:00Z").getUTCDay()),days=Array.from({length:view==="month"?42:7},(_,i)=>addDays(start,i)),monthEnd=new Date(Date.UTC(Number(first.slice(0,4)),Number(first.slice(5,7)),0,12)).toISOString().slice(0,10);
 const list=filtered.filter(e=>eventDate(e)<=monthEnd&&(e.schedule.end?.date??eventDate(e))>=first),selectedEvents=eventsOn(filtered,selected);
 function move(n:number){let next;if(view==="week")next=addDays(date,7*n);else{const d=new Date(first+"T12:00:00Z");d.setUTCMonth(d.getUTCMonth()+n);next=d.toISOString().slice(0,10)}setDate(next);setSelected(next)}
 function beginDrag(e:React.DragEvent<HTMLButtonElement>,event:CalendarEvent){if(!canEdit||busy)return;e.dataTransfer.setData("text/plain",event.id);e.dataTransfer.effectAllowed="move";setDraggingId(event.id);setDropDate(null)}
 function dropOn(dateValue:string){if(!draggingId)return;const event=events.find(e=>e.id===draggingId);setDraggingId(null);setDropDate(null);if(!event||eventDate(event)===dateValue)return;suppressClick.current=true;window.setTimeout(()=>{suppressClick.current=false},0);void onMove(event,dateValue)}
 function chip(event:CalendarEvent,compact=false){
  const p=event.schedule.start??event.schedule.end!;
  return <div key={event.id} className={'event-item '+event.type+(compact?' compact':'')}>
   <button type="button" draggable={canEdit&&!busy} className={'event-chip '+event.type+(compact?' compact':'')+(draggingId===event.id?' dragging':'')} title={event.companyName+" · "+event.title+" · "+formatPoint(p)} onDragStart={e=>beginDrag(e,event)} onDragEnd={()=>{setDraggingId(null);setDropDate(null)}} onClick={e=>{if(suppressClick.current){e.preventDefault();suppressClick.current=false;return}onOpen(event)}}>
   <span className="event-dot"/><strong>{compact?event.companyName:event.companyName+" · "+event.title}</strong>{compact&&<span className="event-kind">{eventLabels[event.type]}</span>}<time>{compact?p.time??"":formatPoint(p)}{!compact&&event.schedule.end&&event.schedule.start?" ~ "+formatPoint(event.schedule.end):""}</time>{!compact&&<small>{eventLabels[event.type]}{event.schedule.tentative?" · 예정":""}</small>}
   </button>
   {canEdit&&!compact&&<details className="event-date-editor" onClick={e=>e.stopPropagation()}><summary aria-label={event.title+" 날짜 변경"}>날짜 변경</summary><div><label>변경할 날짜<input type="date" defaultValue={eventDate(event)} disabled={busy} onChange={e=>{if(e.target.value){void onMove(event,e.target.value);e.currentTarget.closest("details")?.removeAttribute("open")}}}/></label></div></details>}
  </div>
 }
 return <section className="calendar"><div className="calendar-toolbar"><h2>{date.slice(0,4)}년 {Number(date.slice(5,7))}월{view==="week"&&<small> · {start.slice(5)}부터 7일</small>}</h2><div className="calendar-controls"><button onClick={()=>{setDate(kstDate());setSelected(kstDate())}}>오늘</button><button onClick={()=>move(-1)} aria-label="이전 기간">‹</button><button onClick={()=>move(1)} aria-label="다음 기간">›</button><div className="tabs">{[["month","월간"],["week","주간"],["list","목록"]].map(([v,l])=><button key={v} aria-pressed={view===v} className={view===v?"active":""} onClick={()=>setView(v)}>{l}</button>)}</div></div></div>
  <div className="calendar-filters"><select aria-label="기업 필터" value={company} onChange={e=>setCompany(e.target.value)}><option value="">전체 기업</option>{[...new Set(events.map(e=>e.companyName))].map(c=><option key={c}>{c}</option>)}</select><details className="filter-popover"><summary>일정 유형 <span>{types.length}</span>⌄</summary><div><button onClick={()=>setTypes(types.length?[]:Object.keys(eventLabels))}>{types.length?"전체 해제":"전체 선택"}</button>{Object.entries(eventLabels).map(([v,l])=><label key={v} className="check"><input type="checkbox" checked={types.includes(v)} onChange={e=>setTypes(e.target.checked?[...types,v]:types.filter(t=>t!==v))}/>{l}</label>)}</div></details><input aria-label="기준 날짜" type="date" value={date} onChange={e=>{if(e.target.value){setDate(e.target.value);setSelected(e.target.value)}}}/><span className="calendar-key">모집 시작·마감과 실제 전형 일정만 표시</span></div>
  {upcoming.length>0&&<aside className="calendar-upcoming" aria-label="앞으로 7일 일정"><div><strong>앞으로 7일</strong><span>아직 처리하지 않은 일정</span></div><div className="upcoming-list">{upcoming.slice(0,6).map(e=><button key={e.id} type="button" onClick={()=>onOpen(e)}><time>{eventDate(e).slice(5)}{(e.schedule.start??e.schedule.end)?.time&&<small> {(e.schedule.start??e.schedule.end)?.time}</small>}</time><span><strong>{e.companyName}</strong><small>{eventLabels[e.type]} · {e.title}</small></span></button>)}</div></aside>}
  {undatedApplications.length>0&&<aside className="undated-panel" aria-label="일정 미정 공고"><div><strong>일정 미정 공고 {undatedApplications.length}개</strong><span>날짜를 입력하지 않은 공고도 여기서 확인할 수 있습니다.</span></div><div className="undated-list">{undatedApplications.map(a=><button key={a.id} type="button" onClick={()=>onOpenApplication(a)}><strong>{a.companyName}</strong><span>{a.postingTitle}</span></button>)}</div></aside>}
  {view==="list"?<div className="agenda">{list.length?list.map(e=>chip(e)):<p className="empty">이 달에 표시할 일정이 없습니다.</p>}</div>:<><div className={'calendar-grid '+(view==="week"?"week-grid":"")}>{days.map(d=>{const es=eventsOn(filtered,d);return <div className={'day-cell '+(d===kstDate()?"today ":"")+(d===selected?"selected ":"")+(d.slice(0,7)!==date.slice(0,7)?"outside ":"")+(dropDate===d?"drop-target":"")} key={d} onDragOver={e=>{if(canEdit&&draggingId){e.preventDefault();setDropDate(d)}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDropDate(null)}} onDrop={e=>{e.preventDefault();dropOn(d)}}><button className="day-number" onClick={()=>setSelected(d)} aria-label={d+" 일정 "+es.length+"개"}><span>{Number(d.slice(8))}</span><small>{["일","월","화","수","목","금","토"][new Date(d+"T12:00:00Z").getUTCDay()]}</small></button><div className="cell-events">{es.slice(0,view==="month"?3:1000).map(e=>chip(e,view==="month"))}{view==="month"&&es.length>3&&<button className="more" onClick={()=>setSelected(d)}>+{es.length-3}개 더보기</button>}</div>{es.length>0&&<button className="mobile-count" aria-label={d+" 일정 목록"} onClick={()=>setSelected(d)}>{es.length}개</button>}</div>})}</div><div className="day-list"><h3>{selected.slice(5).replace("-","월 ")}일 <span>{selectedEvents.length}개 일정</span></h3>{selectedEvents.length?selectedEvents.map(e=>chip(e)):<p className="hint">등록된 일정이 없습니다. 여유롭게 다음 일정을 준비하세요.</p>}</div></>}
 </section>
}
