"use client";

import {addDays,due,eventDate,eventLabels,stageKind,type Application,type CalendarEvent} from "@/lib/applications";
import {formatPoint,kstDate} from "@/lib/jobs";
import type {QuickView} from "./calendar";

type DashboardProps={apps:Application[];upcoming:CalendarEvent[];now:number;onOpen:(application:Application)=>void;onCalendar:(quick:QuickView)=>void;onBoard:()=>void};

export function Dashboard({apps,upcoming,now,onOpen,onCalendar,onBoard}:DashboardProps){
 const today=kstDate(now),weekEnd=addDays(today,6),todayTasks=apps.flatMap(application=>(application.preparationItems??[]).filter(item=>!item.completedAt&&item.date?.date===today).map(item=>({application,item}))),unsubmitted=apps.filter(application=>{const document=application.stages.find(stage=>stageKind(stage.name)==="document"&&stage.applicable);return due(application,now).urgent&&!document?.status.match(/completed|passed|failed/)}),weekStages=upcoming.filter(event=>['exam','interview','stage'].includes(event.type)&&eventDate(event)<=weekEnd),waiting=apps.flatMap(application=>application.stages.filter(stage=>stage.applicable&&stage.status==="completed"&&!stage.resultConfirmedAt).map(stage=>({application,stage})));
 const findApp=(event:CalendarEvent)=>apps.find(application=>application.id===event.applicationId)!;
 return <div className="dashboard-page"><section className="dashboard-action-strip" aria-label="이번 주 실행 현황"><button type="button" onClick={()=>onCalendar("today")}><span>오늘 준비</span><strong>{todayTasks.length}</strong></button><button type="button" onClick={()=>onCalendar("unsubmitted")}><span>미제출 임박</span><strong>{unsubmitted.length}</strong></button><button type="button" onClick={()=>onCalendar("week")}><span>이번 주 전형</span><strong>{weekStages.length}</strong></button><button type="button" onClick={()=>onCalendar("results")}><span>결과 대기</span><strong>{waiting.length}</strong></button></section>
 <div className="dashboard-grid dashboard-four"><section className="dashboard-section kind-personal"><div className="section-heading"><div><h2>오늘 할 준비</h2><p>날짜를 오늘로 정한 미완료 항목입니다.</p></div><button type="button" onClick={()=>onCalendar("today")}>캘린더 ↗</button></div>{todayTasks.length?<div className="dashboard-list">{todayTasks.slice(0,5).map(({application,item})=><button type="button" key={item.id} onClick={()=>onOpen(application)}><span><strong>{item.title}</strong><small>{application.companyName} · {application.postingTitle}</small></span><time>오늘</time></button>)}</div>:<p className="empty compact-empty">오늘로 정한 준비 항목이 없습니다.</p>}</section>
 <section className="dashboard-section kind-document"><div className="section-heading"><div><h2>미제출 임박 마감</h2><p>3일 안에 마감되고 서류 제출 완료가 아닌 공고입니다.</p></div><button type="button" onClick={onBoard}>전형 보드 ↗</button></div>{unsubmitted.length?<div className="dashboard-list">{unsubmitted.slice(0,5).map(application=><button type="button" key={application.id} onClick={()=>onOpen(application)}><span><strong>{application.companyName}</strong><small>{application.postingTitle}</small></span><time>{formatPoint(application.recruitment.end)}</time></button>)}</div>:<p className="empty compact-empty">미제출 임박 공고가 없습니다.</p>}</section>
 <section className="dashboard-section kind-interview"><div className="section-heading"><div><h2>이번 주 전형</h2><p>시험·면접 등 참석할 전형 일정입니다.</p></div><button type="button" onClick={()=>onCalendar("week")}>캘린더 ↗</button></div>{weekStages.length?<div className="dashboard-list">{weekStages.slice(0,5).map(event=><button type="button" key={event.id} onClick={()=>onOpen(findApp(event))}><span><strong>{event.companyName}</strong><small>{event.title===eventLabels[event.type]?event.title:eventLabels[event.type]+" · "+event.title}</small></span><time>{eventDate(event).slice(5)}</time></button>)}</div>:<p className="empty compact-empty">이번 주 전형 일정이 없습니다.</p>}</section>
 <section className="dashboard-section kind-result"><div className="section-heading"><div><h2>결과 대기</h2><p>응시·제출 완료 후 결과를 기록하지 않은 전형입니다.</p></div><button type="button" onClick={onBoard}>전형 보드 ↗</button></div>{waiting.length?<div className="dashboard-list">{waiting.slice(0,5).map(({application,stage})=><button type="button" key={stage.id} onClick={()=>onOpen(application)}><span><strong>{application.companyName}</strong><small>{stage.name} · 완료와 합격은 별도</small></span><time>{stage.resultExpectedAt?formatPoint(stage.resultExpectedAt):"발표일 미정"}</time></button>)}</div>:<p className="empty compact-empty">결과를 기다리는 전형이 없습니다.</p>}</section></div>
 {!apps.length&&<div className="empty welcome"><h2>첫 공고를 추가해보세요</h2><p>캘린더에서 마감과 전형 일정을 한곳에 관리할 수 있습니다.</p></div>}</div>
}
