"use client";
import {useEffect,useRef,useState} from "react";
import {addDays,calendarEvents,emptyRange,eventDate,eventLabels,managementLabels,newStage,point,stageKind,stageLabels,type Application,type Point,type Range,type StageStatus} from "@/lib/applications";
import {patchProgress,mergeProgressDraft,type ProgressPatch} from '@/lib/progress';
import {formatPoint,kstDate} from "@/lib/jobs";
import type {PostingAnalysis} from "@/lib/posting-analysis";

export function Modal({title,children,onClose,drawer=false,className=''}:{drawer?:boolean;className?:string;title:string;children:React.ReactNode;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>{previous?.focus()}},[]);
 return <dialog ref={ref} className={"editor-dialog "+(drawer?"drawer ":'')+className} onCancel={e=>{e.preventDefault();onClose()}} aria-label={title}><div className="dialog-head"><h2>{title}</h2><button type="button" onClick={onClose} aria-label="닫기">×</button></div>{children}</dialog>
}
export function PointField({label,value,onChange}:{label:string;value:Point|null;onChange:(v:Point|null)=>void}){
 return <div className="point-field"><label>{label}<input type="date" value={value?.date??""} onChange={e=>onChange(e.target.value?{...(value??{time:null,timezone:"Asia/Seoul"}),date:e.target.value,timezone:"Asia/Seoul"}:null)}/></label><label>시각 (선택)<input type="time" disabled={!value} value={value?.time??""} onChange={e=>value&&onChange({...value,time:e.target.value||null})}/></label></div>
}
/** 후속 전형은 날짜만 편집한다. 기존에 저장된 시각·초·메모는 객체에 남겨 둔다. */
export function DateOnlyPointField({label,value,onChange}:{label:string;value:Point|null;onChange:(v:Point|null)=>void}){
 return <label className="date-only-field">{label}<input type="date" value={value?.date??""} onChange={e=>onChange(e.target.value?{...(value??{time:null,timezone:"Asia/Seoul"}),date:e.target.value,timezone:"Asia/Seoul"}:null)}/></label>
}
export function RangeField({value,onChange}:{value:Range;onChange:(v:Range)=>void}){return <div className="range-fields"><PointField label="시작일 (선택)" value={value.start} onChange={start=>onChange({...value,start})}/><PointField label="종료일 (선택)" value={value.end} onChange={end=>onChange({...value,end})}/><label className="check"><input type="checkbox" checked={value.tentative} onChange={e=>onChange({...value,tentative:e.target.checked})}/>미확정·예정 일정</label></div>}
export function DateOnlyRangeField({value,onChange}:{value:Range;onChange:(v:Range)=>void}){
 const hasPeriod=!!value.end;
 return <div className="date-only-range"><DateOnlyPointField label="일정 날짜" value={value.start} onChange={start=>onChange({...value,start})}/>{hasPeriod?<DateOnlyPointField label="종료 날짜" value={value.end} onChange={end=>onChange({...value,end})}/>:<button type="button" className="text-button" onClick={()=>onChange({...value,end:value.start?{...value.start}:null})} disabled={!value.start}>기간으로 입력</button>}<label className="check"><input type="checkbox" checked={value.tentative} onChange={e=>onChange({...value,tentative:e.target.checked})}/>미확정·예정 일정</label></div>
}
export function Editor({application,isNew,onSave,onDelete,onClose,focusId,focusLabel,onProgress,sessionTag,readOnly=false}:{onProgress:(patch:ProgressPatch)=>Promise<Application>;readOnly?:boolean;application:Application;isNew:boolean;onSave:(a:Application,allowDuplicate:boolean)=>Promise<void>;onDelete:()=>Promise<void>;onClose:()=>void;focusId?:string;focusLabel?:string;sessionTag:string}){
 const [draft,setDraft]=useState(()=>structuredClone(application)),[busy,setBusy]=useState(false),[error,setError]=useState(""),[duplicate,setDuplicate]=useState(false),[resultFields,setResultFields]=useState<Record<string,boolean>>({});
 const baseline=useRef(structuredClone(application)),queue=useRef<ProgressPatch[]>([]),processing=useRef(false);
 const [quickBusy,setQuickBusy]=useState(false),[quickNotice,setQuickNotice]=useState(''),[retry,setRetry]=useState<ProgressPatch|null>(null);
 const [taskTitle,setTaskTitle]=useState(''),[taskDate,setTaskDate]=useState(''),[taskCalendar,setTaskCalendar]=useState(false),[refresh,setRefresh]=useState<PostingAnalysis|null>(null),[refreshFields,setRefreshFields]=useState<Record<string,boolean>>({}),[refreshBusy,setRefreshBusy]=useState(false),[refreshError,setRefreshError]=useState('');
 async function drain(){if(processing.current)return;processing.current=true;setQuickBusy(true);
  while(queue.current.length){const change=queue.current.shift()!;try{
    const saved=await onProgress(change);baseline.current=mergeProgressDraft(baseline.current,saved,change);
    setDraft(current=>{let next=mergeProgressDraft(current,saved,change);for(const queued of queue.current)next=patchProgress(next,queued);return next});
    setQuickNotice('저장했습니다.');setRetry(null);
   }catch(e){setDraft(current=>{let next=mergeProgressDraft(current,baseline.current,change);for(const queued of queue.current)next=patchProgress(next,queued);return next});setQuickNotice(e instanceof Error?e.message:'상태 저장 실패');setRetry(change)}
  }processing.current=false;setQuickBusy(false);
 }
 function quick(change:ProgressPatch){try{patchProgress(draft,change);setDraft(current=>patchProgress(current,change));queue.current.push(change);setQuickNotice('저장 중…');void drain()}catch(e){setQuickNotice(e instanceof Error?e.message:'변경 값을 확인해주세요.')}}
 const currentStage=draft.stages.find(s=>s.id===draft.currentStageId&&s.applicable);
 const nextEvent=calendarEvents([draft]).find(e=>eventDate(e)>=kstDate());
 function set<K extends keyof Application>(key:K,value:Application[K]){setDraft(a=>({...a,[key]:value}))}
 function stage(id:string,patch:Partial<Application["stages"][number]>){set("stages",draft.stages.map(s=>s.id===id?{...s,...patch}:s))}
 function progressOrDraft(change:ProgressPatch){if(isNew){setDraft(current=>patchProgress(current,change));return}quick(change)}
 function addPreparation(title=taskTitle,date=taskDate){const value=title.trim();if(!value){setError('준비 항목 제목을 입력해주세요.');return}const now=new Date().toISOString(),item={id:crypto.randomUUID(),title:value,date:date?{date,time:null,timezone:'Asia/Seoul' as const}:null,showOnCalendar:!!date&&taskCalendar,completedAt:null,createdAt:now};set('preparationItems',[...(draft.preparationItems??[]),item]);setTaskTitle('');setTaskDate('');setTaskCalendar(false)}
 function suggest(title:string,date:string){if(date<kstDate()){setError('과거 날짜에는 준비 항목을 제안하지 않습니다.');return}setTaskTitle(title);setTaskDate(date);setTaskCalendar(true)}
 async function analyzeSource(){if(!draft.postingUrl){setRefreshError('공고 URL을 먼저 입력해주세요.');return}setRefreshBusy(true);setRefreshError('');try{const response=await fetch('/api/posting-analysis',{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Session':sessionTag},body:JSON.stringify({url:draft.postingUrl})}),payload=JSON.parse(await response.text()) as PostingAnalysis&{error?:string};if(!response.ok)throw new Error(payload.error);setRefresh(payload);setRefreshFields({companyName:!draft.companyName&&!!payload.companyName,postingTitle:!draft.postingTitle&&!!payload.postingTitle,role:!draft.role&&!!payload.role,employmentType:!draft.employmentType&&!!payload.employmentType,start:!!payload.start&&JSON.stringify(payload.start)!==JSON.stringify(draft.recruitment.start),end:!!payload.end&&JSON.stringify(payload.end)!==JSON.stringify(draft.recruitment.end),stages:payload.stages.some(found=>!!found.date)})}catch(e){setRefreshError(e instanceof Error?e.message:'원문 정보를 확인하지 못했습니다.')}finally{setRefreshBusy(false)}}
 function applyRefresh(){if(!refresh)return;setDraft(current=>{const next=structuredClone(current);if(refreshFields.companyName&&refresh.companyName)next.companyName=refresh.companyName;if(refreshFields.postingTitle&&refresh.postingTitle)next.postingTitle=refresh.postingTitle;if(refreshFields.role&&refresh.role)next.role=refresh.role;if(refreshFields.employmentType&&refresh.employmentType)next.employmentType=refresh.employmentType;if(refreshFields.start&&refresh.start)next.recruitment.start=point(refresh.start);if(refreshFields.end&&refresh.end)next.recruitment.end=point(refresh.end);next.fieldEvidence={...next.fieldEvidence,...Object.fromEntries(Object.entries(refresh.evidence).filter(([key])=>refreshFields[key]||key==='recruitmentStart'&&refreshFields.start||key==='recruitmentEnd'&&refreshFields.end))};next.officialCheckedAt=refresh.checkedAt;if(refreshFields.stages)for(const found of refresh.stages){let item=next.stages.find(stage=>stage.name===found.name);if(!item){item=newStage(found.name,next.stages.length);next.stages.push(item)}if(found.date&&!item.schedule.start&&!item.schedule.end)item.schedule={start:point(found.date),end:null,tentative:false}}return next});setRefresh(null);setQuickNotice('선택한 제안을 편집본에 반영했습니다. 아래 저장 버튼을 눌러 확정하세요.')}
 useEffect(()=>{if(focusId)document.getElementById(focusId)?.scrollIntoView({block:"center"})},[focusId]);
 async function save(e:React.FormEvent){e.preventDefault();if(busy||quickBusy||readOnly)return;setBusy(true);setError("");try{await onSave(draft,duplicate)}catch(e){setError(e instanceof Error?e.message:"저장 실패")}finally{setBusy(false)}}
 function close(){if(processing.current)return;if(JSON.stringify(draft)!==JSON.stringify(baseline.current)&&!confirm("저장하지 않은 변경이 있습니다. 닫을까요?"))return;onClose()}
 function reveal(target:string){const details=document.querySelector<HTMLDetailsElement>(".advanced-details");if(details)details.open=true;requestAnimationFrame(()=>document.getElementById(target)?.scrollIntoView({block:"center",behavior:"smooth"}))}
 async function remove(){if(!confirm(draft.companyName+" 공고와 전형 "+draft.stages.length+"개, 연결 일정 "+calendarEvents([draft]).length+"개를 삭제할까요?"))return;setBusy(true);try{await onDelete()}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <Modal drawer title={isNew?"공고 직접 등록":draft.companyName+" · 공고 상세"} onClose={close}>
 <section className="editor-overview" aria-label="공고 진행 요약"><div className="overview-heading"><span className="eyebrow">진행 요약</span><h3>{draft.companyName||"새 공고"}<span> · </span>{draft.postingTitle||"공고명을 입력하세요"}</h3></div>
 {isNew?<p className="hint">기업명과 공고명만 저장한 뒤 전형을 선택할 수 있습니다.</p>:<><div className="quick-progress"><label>현재 전형<select aria-label="현재 전형 빠른 변경" value={draft.currentStageId??''} disabled={busy||readOnly} onChange={e=>quick({currentStageId:e.target.value||null})}><option value="">아직 선택하지 않음</option>{draft.stages.filter(s=>s.applicable).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>진행 상태<select aria-label="진행 상태 빠른 변경" value={currentStage?.status??''} disabled={!currentStage||busy||readOnly} onChange={e=>currentStage&&quick({stageId:currentStage.id,stageStatus:e.target.value as StageStatus})}>{!currentStage&&<option value="">전형을 먼저 선택하세요</option>}{Object.entries(stageLabels).filter(([key])=>key!=='not_applicable').map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div>
 <div className="quick-feedback"><span role="status" aria-live="polite">{quickBusy?'저장 중…':quickNotice||'선택하면 바로 저장됩니다. 완료와 합격은 별도입니다.'}</span>{retry&&!quickBusy&&<button type="button" onClick={()=>quick(retry)}>다시 저장</button>}{draft.stages.find(s=>s.name==='서류 제출'&&s.applicable)&&<button type="button" disabled={busy||quickBusy||readOnly} onClick={()=>{const documentStage=draft.stages.find(s=>s.name==='서류 제출'&&s.applicable)!;quick({currentStageId:documentStage.id,stageId:documentStage.id,stageStatus:'completed'})}}>서류 제출 완료</button>}</div></>}
 <div className="overview-next"><span>다음 일정</span><strong>{nextEvent?eventLabels[nextEvent.type]+' · '+formatPoint(nextEvent.schedule.start??nextEvent.schedule.end):'다음 일정 미정'}</strong></div>{focusLabel&&<p className="overview-context">선택한 일정: {focusLabel}</p>}<div className="row-actions"><button type="button" onClick={()=>reveal(currentStage?.id??'application-status')}>전형 기록과 일정 편집</button></div></section>
 <form onSubmit={save}><fieldset disabled={busy||readOnly}>
 <details className="basic-details" open={isNew}><summary>공고 기본 정보 수정 <span className="badge">기업명 · 공고명 · 원문 링크</span></summary><section className="edit-section"><p className="hint">기업명과 공고명만 먼저 입력해도 저장할 수 있습니다. 나머지는 나중에 채워도 됩니다.</p><div className="form-grid"><label>기업명 *<input required maxLength={100} value={draft.companyName} onChange={e=>set("companyName",e.target.value)}/></label><label>공고명 *<input required maxLength={200} value={draft.postingTitle} onChange={e=>set("postingTitle",e.target.value)}/></label><label className="full">공고 URL (선택)<input type="url" placeholder="https://" value={draft.postingUrl??""} onChange={e=>set("postingUrl",e.target.value||null)}/></label></div>{draft.postingUrl&&<a className="text-link" href={draft.postingUrl} target="_blank" rel="noreferrer">공고 원문 열기 ↗</a>}</section></details>
 <details className="advanced-details"><summary>상세 입력 <span className="badge">직무 · 모집 기간 · 전형 · 메모</span></summary><div className="advanced-details-body"><section className="edit-section"><h3>직무와 채용 구분</h3><div className="form-grid"><label>직무<input value={draft.role} onChange={e=>set("role",e.target.value)}/></label><label>채용 구분<input placeholder="신입 · 경력 · 인턴" value={draft.employmentType} onChange={e=>set("employmentType",e.target.value)}/></label></div></section>
 <section className="edit-section" id="recruitment"><h3>모집 일정 상세</h3><p className="hint">모집 일정은 정확한 시각까지 입력할 수 있습니다. 모르면 비워두세요. 모든 일정은 한국시간입니다.</p><RangeField value={draft.recruitment} onChange={v=>set("recruitment",v)}/><p className="hint">{draft.sourceName??(draft.origin==="official"?"공식 조회 정보":draft.origin==="public"?"공개 채용정보":"직접 입력 정보")}{draft.discoveredBy?" · 발견: "+draft.discoveredBy:""}{draft.officialCheckedAt?" · 확인 "+new Date(draft.officialCheckedAt).toLocaleString("ko-KR",{timeZone:"Asia/Seoul"}):""}</p>{draft.evidence&&<p className="hint">{draft.evidence}</p>}{draft.officialRecruitmentSnapshot&&<button type="button" onClick={()=>set("recruitment",structuredClone(draft.officialRecruitmentSnapshot!))}>조회한 원본 일정으로 되돌리기</button>}</section>
 <section className="edit-section" id="application-status"><h3>지원 진행 상황</h3><div className="form-grid"><label>전체 관리 상태<select value={draft.managementStatus} onChange={e=>progressOrDraft({managementStatus:e.target.value as Application["managementStatus"]})}>{Object.entries(managementLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>현재 전형<select value={draft.currentStageId??""} onChange={e=>progressOrDraft({currentStageId:e.target.value||null})}><option value="">선택하지 않음</option>{draft.stages.filter(s=>s.applicable).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><p className="hint">완료는 제출·응시를 마친 상태입니다. 합격과 전체 관리 상태는 직접 선택합니다.</p>
 {draft.stages.map((s,i)=><details className={`stage-editor kind-${stageKind(s.name)}`} key={s.id} id={s.id} open={focusId===s.id||(!focusId&&currentStage?.id===s.id)||undefined}><summary><span><i className="stage-symbol" aria-hidden="true"/>{i+1}. {s.name}</span><span className={`status-badge status-${s.status}`}>{stageLabels[s.status]}{draft.currentStageId===s.id?" · 현재":""}</span></summary><div className="stage-body"><div className="stage-primary"><strong>{s.name}</strong><label>전형 상태<select value={s.status} onChange={e=>{const status=e.target.value as StageStatus;if(status==="not_applicable"&&draft.currentStageId===s.id){setError("현재 전형을 먼저 해제한 뒤 해당 없음으로 설정해주세요.");return}progressOrDraft({stageId:s.id,stageStatus:status})}}>{Object.entries(stageLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><div className="stage-schedule"><DateOnlyRangeField value={s.schedule} onChange={schedule=>stage(s.id,{schedule})}/>{s.resultExpectedAt||resultFields[s.id]?<DateOnlyPointField label="결과 발표 예정일" value={s.resultExpectedAt} onChange={resultExpectedAt=>stage(s.id,{resultExpectedAt})}/>:<button type="button" className="text-button" onClick={()=>setResultFields(x=>({...x,[s.id]:true}))}>결과 발표일 추가</button>}</div><details className="stage-more"><summary>더보기</summary><div className="row-actions"><label>전형명<input required value={s.name} onChange={e=>stage(s.id,{name:e.target.value})}/></label><button type="button" disabled={!s.applicable||isNew} onClick={()=>progressOrDraft({currentStageId:s.id})}>현재 전형으로</button><button type="button" disabled={i===0} onClick={()=>{const list=[...draft.stages];[list[i-1],list[i]]=[list[i],list[i-1]];set("stages",list.map((x,j)=>({...x,order:j})))}}>↑ 위로</button><button type="button" disabled={i===draft.stages.length-1} onClick={()=>{const list=[...draft.stages];[list[i+1],list[i]]=[list[i],list[i+1]];set("stages",list.map((x,j)=>({...x,order:j})))}}>↓ 아래로</button><button type="button" onClick={()=>{if(s.status==="not_applicable"){progressOrDraft({stageId:s.id,stageStatus:"not_started"});return}if(draft.currentStageId===s.id){setError("현재 전형을 먼저 해제한 뒤 해당 없음으로 설정해주세요.");return}progressOrDraft({stageId:s.id,stageStatus:"not_applicable"})}}>해당 없음</button><button className="danger" type="button" onClick={()=>{if(!confirm(s.name+" 전형을 삭제할까요? 기존 일정·결과·메모는 데이터에서 보존되지 않고 삭제됩니다."))return;setDraft(a=>({...a,currentStageId:a.currentStageId===s.id?null:a.currentStageId,stages:a.stages.filter(x=>x.id!==s.id).map((x,j)=>({...x,order:j}))}))}}>전형 삭제</button></div></details></div></details>)}
 <button type="button" onClick={()=>set("stages",[...draft.stages,newStage("새 전형",draft.stages.length)])}>＋ 전형 추가</button></section>
 <section className="edit-section preparation-section"><div className="section-heading"><div><h3>준비 체크리스트</h3><p className="hint">완료 체크는 전형 상태나 합격 결과를 바꾸지 않습니다.</p></div></div><div className="preparation-list">{(draft.preparationItems??[]).map(item=><div className={'preparation-row '+(item.completedAt?'completed':'')} key={item.id}><input aria-label={item.title+' 완료'} type="checkbox" checked={!!item.completedAt} onChange={event=>set('preparationItems',(draft.preparationItems??[]).map(value=>value.id===item.id?{...value,completedAt:event.target.checked?new Date().toISOString():null}:value))}/><label>준비 항목<input value={item.title} onChange={event=>set('preparationItems',(draft.preparationItems??[]).map(value=>value.id===item.id?{...value,title:event.target.value}:value))}/></label><label>날짜 (선택)<input type="date" value={item.date?.date??''} onChange={event=>set('preparationItems',(draft.preparationItems??[]).map(value=>value.id===item.id?{...value,date:event.target.value?{date:event.target.value,time:value.date?.time??null,timezone:'Asia/Seoul'}:null,showOnCalendar:event.target.value?value.showOnCalendar:false}:value))}/></label><label className="check"><input type="checkbox" disabled={!item.date} checked={!!item.date&&item.showOnCalendar} onChange={event=>set('preparationItems',(draft.preparationItems??[]).map(value=>value.id===item.id?{...value,showOnCalendar:event.target.checked}:value))}/>캘린더 표시</label><button className="danger" type="button" onClick={()=>set('preparationItems',(draft.preparationItems??[]).filter(value=>value.id!==item.id))}>삭제</button></div>)}</div><div className="preparation-add"><label>새 준비 항목<input value={taskTitle} onChange={event=>setTaskTitle(event.target.value)} placeholder="예: 자기소개서 제출 전 확인"/></label><label>날짜 (선택)<input type="date" value={taskDate} onChange={event=>setTaskDate(event.target.value)}/></label><label className="check"><input type="checkbox" disabled={!taskDate} checked={!!taskDate&&taskCalendar} onChange={event=>setTaskCalendar(event.target.checked)}/>캘린더 표시</label><button type="button" onClick={()=>addPreparation()}>항목 추가</button></div><div className="suggestions">{draft.recruitment.end&&addDays(draft.recruitment.end.date,-3)>=kstDate()&&<button type="button" onClick={()=>suggest('지원서 초안 최종 점검',addDays(draft.recruitment.end!.date,-3))}>마감 3일 전 준비 제안</button>}{currentStage?.schedule.start&&addDays(currentStage.schedule.start.date,-1)>=kstDate()&&<button type="button" onClick={()=>suggest(currentStage.name+' 전날 준비 확인',addDays(currentStage.schedule.start!.date,-1))}>{currentStage.name} 전날 준비 제안</button>}<span>제안은 선택한 뒤 ‘항목 추가’를 눌러야 저장됩니다.</span></div></section>
 <section className="edit-section source-refresh"><div className="section-heading"><div><h3>원문 정보 및 보완</h3><p className="hint">현재 진행 상태·메모·개인 일정은 바꾸지 않고, 선택한 정보만 편집본에 반영합니다.</p></div><button type="button" disabled={!draft.postingUrl||refreshBusy} onClick={()=>void analyzeSource()}>{refreshBusy?'원문 확인 중…':'원문에서 정보 보완'}</button></div>{refreshError&&<p className="error" role="alert">{refreshError}</p>}{refresh&&<div className="refresh-comparison"><label className="check"><input type="checkbox" checked={!!refreshFields.companyName} disabled={!refresh.companyName} onChange={e=>setRefreshFields(value=>({...value,companyName:e.target.checked}))}/>기업명: {draft.companyName||'비어 있음'} → {refresh.companyName||'확인 필요'}</label><label className="check"><input type="checkbox" checked={!!refreshFields.postingTitle} disabled={!refresh.postingTitle} onChange={e=>setRefreshFields(value=>({...value,postingTitle:e.target.checked}))}/>공고명: {draft.postingTitle||'비어 있음'} → {refresh.postingTitle||'확인 필요'}</label><label className="check"><input type="checkbox" checked={!!refreshFields.role} disabled={!refresh.role} onChange={e=>setRefreshFields(value=>({...value,role:e.target.checked}))}/>직무: {draft.role||'비어 있음'} → {refresh.role||'확인 필요'}</label><label className="check"><input type="checkbox" checked={!!refreshFields.employmentType} disabled={!refresh.employmentType} onChange={e=>setRefreshFields(value=>({...value,employmentType:e.target.checked}))}/>채용 구분: {draft.employmentType||'비어 있음'} → {refresh.employmentType||'확인 필요'}</label><label className="check"><input type="checkbox" checked={!!refreshFields.start} disabled={!refresh.start} onChange={e=>setRefreshFields(value=>({...value,start:e.target.checked}))}/>모집 시작: {formatPoint(draft.recruitment.start)} → {formatPoint(refresh.start)}</label><label className="check"><input type="checkbox" checked={!!refreshFields.end} disabled={!refresh.end} onChange={e=>setRefreshFields(value=>({...value,end:e.target.checked}))}/>모집 마감: {formatPoint(draft.recruitment.end)} → {formatPoint(refresh.end)}</label>{refresh.stages.some(stage=>stage.date)&&<label className="check"><input type="checkbox" checked={!!refreshFields.stages} onChange={e=>setRefreshFields(value=>({...value,stages:e.target.checked}))}/>비어 있는 전형 일정 제안 {refresh.stages.filter(stage=>stage.date).length}개</label>}<p className="hint">{refresh.analyzer==='ai'?'AI로 구조화했습니다.':'원문 규칙 분석 결과입니다.'} 선택하지 않은 값과 기존 전형 기록은 유지됩니다.</p><div className="row-actions"><button type="button" className="primary-soft" onClick={applyRefresh}>선택한 제안 적용</button><button type="button" onClick={()=>setRefresh(null)}>건너뛰기</button><a href={refresh.url} target="_blank" rel="noreferrer">원문 열기 ↗</a></div></div>}</section>
 <section className="edit-section"><h3>개인 일정</h3>{draft.personalEvents.map(e=><div className="personal-editor" id={e.id} key={e.id}><label>일정명<input required value={e.title} onChange={v=>set("personalEvents",draft.personalEvents.map(x=>x.id===e.id?{...x,title:v.target.value}:x))}/></label><RangeField value={e.schedule} onChange={schedule=>set("personalEvents",draft.personalEvents.map(x=>x.id===e.id?{...x,schedule}:x))}/><label>일정 메모<textarea value={e.notes} onChange={v=>set("personalEvents",draft.personalEvents.map(x=>x.id===e.id?{...x,notes:v.target.value}:x))}/></label><button className="danger" type="button" onClick={()=>{if(confirm("이 개인 일정을 삭제할까요?"))set("personalEvents",draft.personalEvents.filter(x=>x.id!==e.id))}}>일정 삭제</button></div>)}<button type="button" onClick={()=>set("personalEvents",[...draft.personalEvents,{id:crypto.randomUUID(),title:"",schedule:emptyRange(),notes:""}])}>＋ 개인 일정 추가</button></section>
 <section className="edit-section"><label>공고 메모<textarea rows={4} value={draft.notes} onChange={e=>set("notes",e.target.value)}/></label>{isNew&&<label className="check"><input type="checkbox" checked={duplicate} onChange={e=>setDuplicate(e.target.checked)}/>같은 URL·공고명이 있어도 별도 공고로 등록</label>}</section></div></details>
 </fieldset><div className="save-bar">{error&&<p role="alert" className="error">{error}</p>}{!readOnly&&<button className="primary" disabled={busy||quickBusy}>{busy?"저장 중…":isNew?"내 공고에 저장":"변경 사항 저장"}</button>}<button type="button" disabled={busy||quickBusy} onClick={close}>닫기</button>{!isNew&&!readOnly&&<button type="button" className="danger" disabled={busy||quickBusy} onClick={remove}>공고 삭제</button>}</div></form></Modal>
}

