"use client";
import {useEffect,useRef,useState} from "react";
import {calendarEvents,emptyRange,managementLabels,newStage,stageLabels,type Application,type Point,type Range,type StageStatus} from "@/lib/applications";

export function Modal({title,children,onClose,drawer=false}:{drawer?:boolean;title:string;children:React.ReactNode;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>{previous?.focus()}},[]);
 return <dialog ref={ref} className={"editor-dialog "+(drawer?"drawer":"")} onCancel={e=>{e.preventDefault();onClose()}} aria-label={title}><div className="dialog-head"><h2>{title}</h2><button type="button" onClick={onClose} aria-label="닫기">×</button></div>{children}</dialog>
}
export function PointField({label,value,onChange}:{label:string;value:Point|null;onChange:(v:Point|null)=>void}){
 return <div className="point-field"><label>{label}<input type="date" value={value?.date??""} onChange={e=>onChange(e.target.value?{date:e.target.value,time:value?.time??null,timezone:"Asia/Seoul"}:null)}/></label><label>시각 (선택)<input type="time" disabled={!value} value={value?.time??""} onChange={e=>value&&onChange({...value,time:e.target.value||null,second:undefined})}/></label></div>
}
export function RangeField({value,onChange}:{value:Range;onChange:(v:Range)=>void}){return <div className="range-fields"><PointField label="시작일 (선택)" value={value.start} onChange={start=>onChange({...value,start})}/><PointField label="종료일 (선택)" value={value.end} onChange={end=>onChange({...value,end})}/><label className="check"><input type="checkbox" checked={value.tentative} onChange={e=>onChange({...value,tentative:e.target.checked})}/>미확정·예정 일정</label></div>}
export function Editor({application,isNew,onSave,onDelete,onClose,focusId,readOnly=false}:{readOnly?:boolean;application:Application;isNew:boolean;onSave:(a:Application,allowDuplicate:boolean)=>Promise<void>;onDelete:()=>Promise<void>;onClose:()=>void;focusId?:string}){
 const [draft,setDraft]=useState(()=>structuredClone(application)),[busy,setBusy]=useState(false),[error,setError]=useState(""),[duplicate,setDuplicate]=useState(false);
 function set<K extends keyof Application>(key:K,value:Application[K]){setDraft(a=>({...a,[key]:value}))}
 function stage(id:string,patch:Partial<Application["stages"][number]>){set("stages",draft.stages.map(s=>s.id===id?{...s,...patch}:s))}
 useEffect(()=>{if(focusId)document.getElementById(focusId)?.scrollIntoView({block:"center"})},[focusId]);
 async function save(e:React.FormEvent){e.preventDefault();if(busy||readOnly)return;setBusy(true);setError("");try{await onSave(draft,duplicate)}catch(e){setError(e instanceof Error?e.message:"저장 실패")}finally{setBusy(false)}}
 function close(){if(JSON.stringify(draft)!==JSON.stringify(application)&&!confirm("저장하지 않은 변경이 있습니다. 닫을까요?"))return;onClose()}
 async function remove(){if(!confirm(draft.companyName+" 공고와 전형 "+draft.stages.length+"개, 연결 일정 "+calendarEvents([draft]).length+"개를 삭제할까요?"))return;setBusy(true);try{await onDelete()}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <Modal drawer title={isNew?"공고 직접 등록":draft.companyName+" · 공고 상세"} onClose={close}><form onSubmit={save}><fieldset disabled={busy||readOnly}>
 <section className="edit-section"><h3>공고 기본 정보</h3><div className="form-grid"><label>기업명 *<input required maxLength={100} value={draft.companyName} onChange={e=>set("companyName",e.target.value)}/></label><label>공고명 *<input required maxLength={200} value={draft.postingTitle} onChange={e=>set("postingTitle",e.target.value)}/></label><label>직무<input value={draft.role} onChange={e=>set("role",e.target.value)}/></label><label>채용 구분<input placeholder="신입 · 경력 · 인턴" value={draft.employmentType} onChange={e=>set("employmentType",e.target.value)}/></label><label className="full">공고 URL (선택)<input type="url" placeholder="https://" value={draft.postingUrl??""} onChange={e=>set("postingUrl",e.target.value||null)}/></label></div>{draft.postingUrl&&<a className="text-link" href={draft.postingUrl} target="_blank" rel="noreferrer">공고 원문 열기 ↗</a>}</section>
 <section className="edit-section" id="recruitment"><h3>모집 일정</h3><p className="hint">시각을 모르면 비워두세요. 모든 일정은 한국시간입니다.</p><RangeField value={draft.recruitment} onChange={v=>set("recruitment",v)}/><p className="hint">{draft.sourceName??(draft.origin==="official"?"공식 조회 정보":draft.origin==="public"?"공개 채용정보":"직접 입력 정보")}{draft.officialCheckedAt?" · 확인 "+new Date(draft.officialCheckedAt).toLocaleString("ko-KR",{timeZone:"Asia/Seoul"}):""}</p>{draft.evidence&&<p className="hint">{draft.evidence}</p>}{draft.officialRecruitmentSnapshot&&<button type="button" onClick={()=>set("recruitment",structuredClone(draft.officialRecruitmentSnapshot!))}>조회한 원본 일정으로 되돌리기</button>}</section>
 <section className="edit-section" id="application-status"><h3>지원 진행 상황</h3><div className="form-grid"><label>전체 관리 상태<select value={draft.managementStatus} onChange={e=>set("managementStatus",e.target.value as Application["managementStatus"])}>{Object.entries(managementLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>현재 전형<select value={draft.currentStageId??""} onChange={e=>set("currentStageId",e.target.value||null)}><option value="">선택하지 않음</option>{draft.stages.filter(s=>s.applicable).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><p className="hint">완료는 제출·응시를 마친 상태입니다. 합격과 전체 관리 상태는 직접 선택합니다.</p>
 {draft.stages.map((s,i)=><details className="stage-editor" key={s.id} id={s.id} open={focusId===s.id||undefined}><summary><span>{i+1}. {s.name}</span><span className="badge">{stageLabels[s.status]}{draft.currentStageId===s.id?" · 현재":""}</span></summary><div className="stage-body"><div className="form-grid"><label>전형명<input required value={s.name} onChange={e=>stage(s.id,{name:e.target.value})}/></label><label>전형 상태<select value={s.status} onChange={e=>{const status=e.target.value as StageStatus;if(status==="not_applicable"&&draft.currentStageId===s.id){setError("현재 전형을 먼저 해제한 뒤 해당 없음으로 설정해주세요.");return}stage(s.id,{status,applicable:status!=="not_applicable"})}}>{Object.entries(stageLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><RangeField value={s.schedule} onChange={schedule=>stage(s.id,{schedule})}/><div className="form-grid"><PointField label="결과 발표 예정일" value={s.resultExpectedAt} onChange={resultExpectedAt=>stage(s.id,{resultExpectedAt})}/><PointField label="실제 결과 확인일" value={s.resultConfirmedAt} onChange={resultConfirmedAt=>stage(s.id,{resultConfirmedAt})}/></div><label>전형 메모<textarea value={s.notes} onChange={e=>stage(s.id,{notes:e.target.value})}/></label><div className="row-actions"><button type="button" disabled={!s.applicable} onClick={()=>set("currentStageId",s.id)}>현재 전형으로</button><button type="button" disabled={i===0} onClick={()=>{const list=[...draft.stages];[list[i-1],list[i]]=[list[i],list[i-1]];set("stages",list.map((x,j)=>({...x,order:j})))}}>↑ 위로</button><button type="button" disabled={i===draft.stages.length-1} onClick={()=>{const list=[...draft.stages];[list[i+1],list[i]]=[list[i],list[i+1]];set("stages",list.map((x,j)=>({...x,order:j})))}}>↓ 아래로</button><button className="danger" type="button" onClick={()=>{if(!confirm(s.name+" 전형의 일정·결과·메모도 삭제됩니다. 계속할까요?"))return;setDraft(a=>({...a,currentStageId:a.currentStageId===s.id?null:a.currentStageId,stages:a.stages.filter(x=>x.id!==s.id).map((x,j)=>({...x,order:j}))}))}}>전형 삭제</button></div></div></details>)}
 <button type="button" onClick={()=>set("stages",[...draft.stages,newStage("새 전형",draft.stages.length)])}>＋ 전형 추가</button></section>
 <section className="edit-section"><h3>개인 일정</h3>{draft.personalEvents.map(e=><div className="personal-editor" id={e.id} key={e.id}><label>일정명<input required value={e.title} onChange={v=>set("personalEvents",draft.personalEvents.map(x=>x.id===e.id?{...x,title:v.target.value}:x))}/></label><RangeField value={e.schedule} onChange={schedule=>set("personalEvents",draft.personalEvents.map(x=>x.id===e.id?{...x,schedule}:x))}/><label>일정 메모<textarea value={e.notes} onChange={v=>set("personalEvents",draft.personalEvents.map(x=>x.id===e.id?{...x,notes:v.target.value}:x))}/></label><button className="danger" type="button" onClick={()=>{if(confirm("이 개인 일정을 삭제할까요?"))set("personalEvents",draft.personalEvents.filter(x=>x.id!==e.id))}}>일정 삭제</button></div>)}<button type="button" onClick={()=>set("personalEvents",[...draft.personalEvents,{id:crypto.randomUUID(),title:"",schedule:emptyRange(),notes:""}])}>＋ 개인 일정 추가</button></section>
 <section className="edit-section"><label>공고 메모<textarea rows={4} value={draft.notes} onChange={e=>set("notes",e.target.value)}/></label>{isNew&&<label className="check"><input type="checkbox" checked={duplicate} onChange={e=>setDuplicate(e.target.checked)}/>같은 URL·공고명이 있어도 별도 공고로 등록</label>}</section>
 </fieldset><div className="save-bar">{error&&<p role="alert" className="error">{error}</p>}{!readOnly&&<button className="primary" disabled={busy}>{busy?"저장 중…":isNew?"내 공고에 저장":"변경 사항 저장"}</button>}<button type="button" disabled={busy} onClick={close}>닫기</button>{!isNew&&!readOnly&&<button type="button" className="danger" disabled={busy} onClick={remove}>공고 삭제</button>}</div></form></Modal>
}

