"use client";
import {useState} from 'react';
import {columns,columnFor,type Column} from '@/lib/kanban';
import {due,type Application,type CalendarEvent} from '@/lib/applications';
import {formatPoint} from '@/lib/jobs';
export function JobCard({application:a,next,now,onOpen,onMove,canEdit,busy,allColumns}:{application:Application;next?:CalendarEvent;now:number;onOpen:()=>void;onMove:(column:Column)=>void;canEdit:boolean;busy:boolean;allColumns:Column[]}){
 const d=due(a,now);
 return <article className="job-card" draggable={canEdit&&!busy} onDragStart={e=>{e.dataTransfer.setData('text/plain',a.id);e.dataTransfer.effectAllowed='move';e.currentTarget.classList.add('dragging')}} onDragEnd={e=>e.currentTarget.classList.remove('dragging')}>
 <div className="job-card-top"><span className="company-avatar" aria-hidden="true">{a.companyName.replace(/^(주)|\(주\)/g,'').slice(0,1)}</span><strong title={a.companyName}>{a.companyName}</strong>{canEdit&&<details className="card-menu"><summary aria-label={a.companyName+' 빠른 전형 변경'}>···</summary><div><label>현재 전형 이동<select disabled={busy} value={columnFor(a)} onChange={e=>{const c=allColumns.find(c=>c.id===e.target.value);if(c)onMove(c)}}>{allColumns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div></details>}</div>
 <button className="card-content" onClick={onOpen}><h3 title={a.postingTitle}>{a.postingTitle}</h3>{a.role&&<p className="card-role" title={a.role}>{a.role}</p>}<div className="card-deadline"><span className={'due-badge '+(d.urgent?'urgent':d.closed?'closed':'')}>{d.label}</span><span>{a.recruitment.end?formatPoint(a.recruitment.end):'마감일 확인 필요'}</span></div><div className="card-stage"><span>현재 전형</span><strong>{a.stages.find(s=>s.id===a.currentStageId)?.name??'준비 중'}</strong></div>{next&&<div className="card-next"><span>다음</span><strong>{next.title}</strong><time>{(next.schedule.start??next.schedule.end)?.date.slice(5)} {(next.schedule.start??next.schedule.end)?.time}</time></div>}</button></article>
}
export function Kanban({apps,allApps,upcoming,now,onOpen,onMove,canEdit,busy}:{apps:Application[];allApps:Application[];upcoming:CalendarEvent[];now:number;onOpen:(a:Application)=>void;onMove:(a:Application,c:Column)=>void;canEdit:boolean;busy:boolean}){
 const cols=columns(allApps),[over,setOver]=useState<string|null>(null);
 return <div className="kanban" aria-label="전형별 공고 보드">{cols.map(c=>{const items=apps.filter(a=>columnFor(a)===c.id);return <section key={c.id} className={'kanban-column '+c.kind+(over===c.id?' drag-over':'')} onDragOver={e=>{if(canEdit&&!busy){e.preventDefault();e.dataTransfer.dropEffect='move';setOver(c.id)}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setOver(null)}} onDrop={e=>{e.preventDefault();setOver(null);if(!canEdit||busy)return;const a=allApps.find(a=>a.id===e.dataTransfer.getData('text/plain'));if(a&&columnFor(a)!==c.id)onMove(a,c)}}><div className="column-heading"><span className="status-dot"/><h2>{c.name}</h2><span className="column-count">{items.length}</span></div><div className="column-cards">{items.map(a=><JobCard key={a.id} application={a} now={now} next={upcoming.find(e=>e.applicationId===a.id)} onOpen={()=>onOpen(a)} onMove={column=>onMove(a,column)} canEdit={canEdit} busy={busy} allColumns={cols}/>)}{!items.length&&<p className="column-empty">{canEdit?'카드를 이곳으로 이동':'공고 없음'}</p>}</div></section>})}</div>
}

