"use client";
import {useState} from 'react';
import {columns,columnFor,type Column} from '@/lib/kanban';
import {due,managementLabels,stageKind,stageLabels,type Application,type CalendarEvent} from '@/lib/applications';
import {formatPoint} from '@/lib/jobs';
export function JobCard({application:a,next,now,onOpen,onMove,onFavorite,canEdit,busy,allColumns,showStage=true}:{application:Application;next?:CalendarEvent;now:number;onOpen:()=>void;onMove:(column:Column)=>void;onFavorite?:()=>void;canEdit:boolean;busy:boolean;allColumns:Column[];showStage?:boolean}){
 const d=due(a,now);
 const current=a.stages.find(s=>s.id===a.currentStageId&&s.applicable);
 return <article className="job-card" draggable={canEdit&&!busy} onDragStart={e=>{e.dataTransfer.setData('text/plain',a.id);e.dataTransfer.effectAllowed='move';e.currentTarget.classList.add('dragging')}} onDragEnd={e=>e.currentTarget.classList.remove('dragging')}>
 <div className="job-card-top"><span className="company-avatar" aria-hidden="true">{a.companyName.replace(/^(주)|\(주\)/g,'').slice(0,1)}</span><strong title={a.companyName}>{a.companyName}</strong>{onFavorite&&<button type="button" className={'favorite-button '+(a.favorite?'active':'')} aria-pressed={!!a.favorite} aria-label={a.favorite?'즐겨찾기 해제':'즐겨찾기 추가'} onClick={onFavorite}>★</button>}{canEdit&&<details className="card-menu"><summary aria-label={a.companyName+' 빠른 전형 변경'}>···</summary><div><label>현재 전형 이동<select disabled={busy} value={columnFor(a)} onChange={e=>{const c=allColumns.find(c=>c.id===e.target.value);if(c)onMove(c)}}>{allColumns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div></details>}</div>
 <button className="card-content" onClick={onOpen}><h3 title={a.postingTitle}>{a.postingTitle}</h3>{a.role&&<p className="card-role" title={a.role}>{a.role}</p>}<div className="card-deadline"><span className={'due-badge '+(d.urgent?'urgent':d.closed?'closed':'')}>{d.label}</span><span>{a.recruitment.end?formatPoint(a.recruitment.end):'마감일 확인 필요'}</span></div>{showStage?<div className={'card-stage '+(current?'kind-'+stageKind(current.name):'')}><span>현재 전형</span><strong>{current?.name??'전형 미선택'}</strong>{current&&<span className={'status-badge status-'+current.status}>{stageLabels[current.status]}</span>}<span className="management-badge">{managementLabels[a.managementStatus]}</span></div>:<div className="card-stage board-card-status"><span className={'status-badge status-'+(current?.status??'not_started')}>{current?stageLabels[current.status]:'전형 미선택'}</span><span className="management-badge">{managementLabels[a.managementStatus]}</span></div>}{next&&<div className="card-next"><span>다음</span><strong>{next.title}</strong><time>{(next.schedule.start??next.schedule.end)?.date.slice(5)} {(next.schedule.start??next.schedule.end)?.time}</time></div>}</button></article>
}
export function Kanban({apps,allApps,upcoming,now,onOpen,onMove,onFavorite,canEdit,busy}:{apps:Application[];allApps:Application[];upcoming:CalendarEvent[];now:number;onOpen:(a:Application)=>void;onMove:(a:Application,c:Column)=>void;onFavorite:(a:Application)=>void;canEdit:boolean;busy:boolean}){
 const cols=columns(allApps),[over,setOver]=useState<string|null>(null),[hideEmpty,setHideEmpty]=useState(false),[archiveOpen,setArchiveOpen]=useState(true);
 const visible=cols.filter(c=>!hideEmpty||apps.some(a=>columnFor(a)===c.id)||c.kind==='preparing');
 return <><div className="kanban-tools"><span>카드 하나를 옮기면 현재 전형과 지원 상태가 함께 저장됩니다.</span><label className="check"><input type="checkbox" checked={hideEmpty} onChange={e=>setHideEmpty(e.target.checked)}/>빈 열 숨기기</label><button type="button" onClick={()=>setArchiveOpen(v=>!v)}>{archiveOpen?'종료 열 접기':'종료 열 펼치기'}</button></div><div className="kanban" aria-label="전형별 공고 보드">{visible.map(c=>{const items=apps.filter(a=>columnFor(a)===c.id).sort((a,b)=>Number(!!b.favorite)-Number(!!a.favorite));const collapsed=c.kind==='archived'&&!archiveOpen,tone=c.kind==='stage'?stageKind(c.name):c.kind==='accepted'?'result':'preparation';return <section key={c.id} className={'kanban-column '+c.kind+' kind-'+tone+(over===c.id?' drag-over':'')+(collapsed?' collapsed':'')} onDragOver={e=>{if(canEdit&&!busy){e.preventDefault();e.dataTransfer.dropEffect='move';setOver(c.id)}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setOver(null)}} onDrop={e=>{e.preventDefault();setOver(null);if(!canEdit||busy)return;const a=allApps.find(a=>a.id===e.dataTransfer.getData('text/plain'));if(a&&columnFor(a)!==c.id)onMove(a,c)}}><div className="column-heading"><span className="status-dot"/><h2>{c.name}</h2><span className="column-count">{items.length}</span></div>{!collapsed&&<div className="column-cards">{items.map(a=><JobCard key={a.id} application={a} now={now} next={upcoming.find(e=>e.applicationId===a.id)} onOpen={()=>onOpen(a)} onMove={column=>onMove(a,column)} onFavorite={()=>onFavorite(a)} showStage={false} canEdit={canEdit} busy={busy} allColumns={cols}/>)}{!items.length&&<p className="column-empty">{canEdit?'카드를 이곳으로 이동':'공고 없음'}</p>}</div>}</section>})}</div></>
}

