"use client";
import {useEffect,useState} from 'react';
export type SessionView={displayName:string;sessionTag:string};
export function NameEntry({children}:{children:(session:SessionView,leave:()=>Promise<void>,legacyCount:number)=>React.ReactNode}){
 const [session,setSession]=useState<SessionView|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[name,setName]=useState(''),[error,setError]=useState(''),[legacyCount,setLegacyCount]=useState(0);
 async function check(){setLoading(true);setError('');try{const r=await fetch('/api/session',{cache:'no-store'}),s=JSON.parse(await r.text());if(!r.ok)throw new Error(s.error);setSession(s.session);setLegacyCount(s.legacyCount??0)}catch(e){setError(e instanceof Error?e.message:'접속 정보를 확인하지 못했습니다.')}finally{setLoading(false)}}
 useEffect(()=>{void check()},[]);
 async function enter(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'enter',name})}),s=JSON.parse(await r.text());if(!r.ok)throw new Error(s.error);setSession(s.session)}catch(e){setError(e instanceof Error?e.message:'다시 시도해주세요.')}finally{setBusy(false)}}
 async function leave(){const r=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Session':session?.sessionTag??''},body:JSON.stringify({action:'leave'})});if(!r.ok&&r.status!==401)throw new Error('이름 전환을 시작하지 못했습니다. 다시 시도해주세요.');setSession(null);setName('');await check()}
 if(session)return <div key={session.sessionTag}>{children(session,leave,legacyCount)}</div>;
 return <main className="name-entry"><section className="name-card"><div className="entry-brand"><span className="brand-mark" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="3" y="4.5" width="18" height="16" rx="3"/><path d="M7 3v4M17 3v4M3 9.5h18M7 13h3M14 13h3M7 17h3"/></svg></span><strong>취준캘린더</strong></div><h1>취업 준비,<br/>내 일정부터 가볍게</h1><p>이름만 입력하면 나만의 캘린더가 열려요.</p>{loading?<p role="status">내 공간을 확인하고 있어요…</p>:<form onSubmit={enter}><label htmlFor="entry-name">이름 또는 별명</label><input id="entry-name" value={name} onChange={e=>setName(e.target.value)} placeholder="예: 지민_취준" maxLength={80} autoComplete="nickname" autoFocus disabled={busy} aria-invalid={!!error} aria-describedby="name-help name-error"/><p id="name-error" role={error?'alert':undefined} className="entry-error">{error}</p><button className="primary" disabled={busy}>{busy?'공간을 여는 중…':'내 캘린더 열기'}</button></form>}<p id="name-help" className="entry-help">다음에도 같은 이름으로 기록을 이어갈 수 있어요.<br/>같은 이름을 아는 사람도 들어올 수 있으니, 구분되는 별명을 사용해 주세요.</p>{!loading&&error&&<button className="text-link" type="button" onClick={()=>void check()}>접속 정보 다시 확인</button>}</section></main>;
}
