"use client";
import {useEffect,useState} from "react";
import {calendarEvents,due,eventDate,isUpcoming,managementLabels,newApplication,type Application,type CalendarEvent,type State} from "@/lib/applications";
import {deadline,formatPoint,kstDate,type Posting} from "@/lib/jobs";
import {Editor,Modal} from "./editor";
import {Calendar} from "./calendar";

export default function Home(){
 const [state,setState]=useState<State|null>(null),[tab,setTab]=useState("dashboard"),[error,setError]=useState(""),[editing,setEditing]=useState<Application|null>(null),[focus,setFocus]=useState<string>(),[adding,setAdding]=useState(false),[company,setCompany]=useState(""),[status,setStatus]=useState(""),[now,setNow]=useState(Date.now());
 async function load(){try{const r=await fetch("/api/state",{cache:"no-store"}),s=JSON.parse(await r.text());if(!r.ok)throw new Error(s.error);setState(s);setError("")}catch(e){setError(String(e))}}
 useEffect(()=>{void load();const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer)},[]);
 async function mutate(body:Record<string,unknown>){if(!state)throw new Error("먼저 데이터를 불러와주세요.");const r=await fetch("/api/state",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,revision:state.revision})}),s=JSON.parse(await r.text());if(r.status===409){await load();throw new Error("다른 화면의 변경을 불러왔습니다. 현재 입력은 유지됩니다. 이 내용으로 덮어쓰려면 다시 저장해주세요.")}if(!r.ok)throw new Error(s.error);setState(s)}
 const apps=state?.applications??[],events=calendarEvents(apps);
 const filtered=apps.filter(a=>(!company||a.companyName===company)&&(!status||a.managementStatus===status)).sort((a,b)=>(a.recruitment.end?.date??"9999").localeCompare(b.recruitment.end?.date??"9999"));
 const upcoming=events.filter(e=>!["recruitment_period","recruitment_start","result_confirmed"].includes(e.type)&&isUpcoming(e,now));
 function openEvent(e:CalendarEvent){setEditing(apps.find(a=>a.id===e.applicationId)!);setFocus(e.stageId??e.personalId??"recruitment")}
 return <main className="workspace"><header><a href="/" className="brand"><span>J</span><strong>JOBTIME</strong></a><nav aria-label="주 메뉴">{[["dashboard","대시보드"],["calendar","취업 캘린더"],["all","내 공고"]].map(([v,l])=><button key={v} aria-current={tab===v?"page":undefined} className={tab===v?"active":""} onClick={()=>setTab(v)}>{l}</button>)}</nav><button className="primary" disabled={!state} onClick={()=>setAdding(true)}>＋ 내 공고 추가</button></header>
 <div className="workspace-content"><div className="page-heading"><div><p className="eyebrow">MY CAREER PLANNER</p><h1>{tab==="calendar"?"나의 취업 캘린더":tab==="all"?"내가 준비하는 공고":"다음 기회를 준비하는 시간"}</h1><p className="hint">{kstDate(now)} · 모든 일정은 한국시간 기준</p></div><a className="export-link" href="/api/export">데이터 백업 ↓</a></div>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>void load()}>다시 불러오기</button></div>}
 {!state?<div className="empty">저장된 공고를 불러오는 중입니다.</div>:tab==="calendar"?<Calendar events={events} onOpen={openEvent}/>:<>
 {tab==="dashboard"&&<><section className="stats">{[["전체 공고",apps.length],["지원 준비",apps.filter(a=>a.managementStatus==="preparing").length],["지원 중",apps.filter(a=>a.managementStatus==="active").length],["3일 이내 마감",apps.filter(a=>due(a,now).urgent).length],["최종합격",apps.filter(a=>a.managementStatus==="accepted").length]].map(([label,count])=><article key={label}><span>{label}</span><strong>{count}</strong></article>)}</section><section className="upcoming"><div className="section-heading"><h2>다가오는 일정</h2><button onClick={()=>setTab("calendar")}>캘린더 보기 ↗</button></div><div className="upcoming-grid">{upcoming.slice(0,4).map(e=><button key={e.id} onClick={()=>openEvent(e)}><span>{eventDate(e)} · {e.schedule.start?.time??"시각 미공개"}</span><strong>{e.companyName}</strong><small>{e.title}</small></button>)}{!upcoming.length&&<p className="hint">공고 상세에서 시험·면접과 개인 일정을 추가해보세요.</p>}</div></section></>}
 <div className="section-heading"><h2>나의 지원 공고</h2><div className="row-actions"><select aria-label="기업 필터" value={company} onChange={e=>setCompany(e.target.value)}><option value="">전체 기업</option>{[...new Set(apps.map(a=>a.companyName))].map(c=><option key={c}>{c}</option>)}</select><select aria-label="전체 관리 상태 필터" value={status} onChange={e=>setStatus(e.target.value)}><option value="">모든 상태</option>{Object.entries(managementLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></div>
 <div className="application-grid">{filtered.map(a=>{const d=due(a,now),next=upcoming.find(e=>e.applicationId===a.id);return <article className="application-card" key={a.id}><div className="card-top"><span className="company-name">{a.companyName}</span><span className={"due "+(d.urgent?"urgent":"")}>{d.label}</span></div><h3>{a.postingTitle}</h3><span className="badge">{managementLabels[a.managementStatus]}</span><dl><div><dt>모집 시작</dt><dd>{formatPoint(a.recruitment.start)}</dd></div><div><dt>모집 마감</dt><dd>{formatPoint(a.recruitment.end)}{a.recruitment.end?.time&&!d.closed&&<small className="remaining">{deadline(a.recruitment,now).label}</small>}</dd></div><div><dt>현재 전형</dt><dd>{a.stages.find(s=>s.id===a.currentStageId)?.name??"선택 전"}</dd></div><div><dt>다음 일정</dt><dd>{next?next.title+" · "+eventDate(next):"예정 일정 없음"}</dd></div></dl><div className="progress-caption"><span>완료·결과 확인</span><span>{a.stages.filter(s=>s.applicable&&["completed","passed","failed"].includes(s.status)).length} / {a.stages.filter(s=>s.applicable).length} 전형</span></div><button className="card-open" onClick={()=>{setEditing(a);setFocus(undefined)}}>공고·전형 관리 →</button></article>})}</div>{!filtered.length&&<div className="empty"><h3>{apps.length?"조건에 맞는 공고가 없습니다.":"첫 지원 공고를 추가해보세요."}</h3><p>공식 공고를 검색하거나 어떤 기업이든 직접 등록할 수 있습니다.</p><button className="primary" onClick={()=>setAdding(true)}>내 공고 추가</button></div>}
 </>}
 <footer>모집 마감과 전형 진행 상태는 별도로 관리합니다. 지원 전 공식 공고를 확인하세요.</footer></div>
 {adding&&<AddDialog onClose={()=>setAdding(false)} onManual={()=>{setAdding(false);setEditing(newApplication());setFocus(undefined)}} onSelect={async(provider,id,allowDuplicate)=>{await mutate({action:"add-selected",provider,postingId:id,allowDuplicate});setAdding(false)}}/>}
 {editing&&<Editor key={editing.id} application={editing} isNew={!apps.some(a=>a.id===editing.id)} focusId={focus} onClose={()=>setEditing(null)} onSave={async(a,allowDuplicate)=>{await mutate({action:"save",application:a,allowDuplicate});setEditing(null)}} onDelete={async()=>{await mutate({action:"delete",id:editing.id});setEditing(null)}}/>}
 </main>
}
function AddDialog({onClose,onManual,onSelect}:{onClose:()=>void;onManual:()=>void;onSelect:(provider:string,id:string,allowDuplicate:boolean)=>Promise<void>}){
 const [duplicate,setDuplicate]=useState(false),[query,setQuery]=useState(""),[result,setResult]=useState<{provider:string;company:string;postings:Posting[];warning?:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 return <Modal title="내 공고 추가" onClose={onClose}><div className="add-options"><div><h3>공식 공고 검색</h3><p className="hint">국민은행 · 기업은행 · 농협은행</p></div><button onClick={onManual}>직접 등록 →<small>모든 기업 · URL 없이도 등록</small></button></div><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query})}),s=JSON.parse(await r.text());if(!r.ok)throw new Error(s.error);setResult(s)}catch(e){setError(String(e))}finally{setBusy(false)}}}><label>기업명 또는 공식 공고 주소<input required value={query} onChange={e=>setQuery(e.target.value)} placeholder="국민은행 또는 https://…"/></label><button className="primary" disabled={busy}>{busy?"확인 중…":"공고 검색"}</button></form>{error&&<p className="error" role="alert">{error}</p>}{result&&<div className="choices"><h3>지원할 공고 하나를 선택하세요</h3><label className="check"><input type="checkbox" checked={duplicate} onChange={e=>setDuplicate(e.target.checked)}/>같은 공고를 별도 차수·직무로 등록</label>{result.warning&&<p className="hint">{result.warning}</p>}{result.postings.map(p=><button disabled={busy} key={p.id} onClick={async()=>{setBusy(true);try{await onSelect(result.provider,p.id,duplicate)}catch(e){setError(String(e))}finally{setBusy(false)}}}><strong>{p.title}</strong><small>{formatPoint(p.end)} 마감</small></button>)}{!result.postings.length&&<p>공고가 없습니다. 직접 등록을 이용해주세요.</p>}</div>}</Modal>
}
