"use client";
import {useEffect,useState} from 'react';
import {calendarEvents,due,eventDate,eventLabels,isUpcoming,managementLabels,moveCalendarEvent,newApplication,type Application,type CalendarEvent,type State} from '@/lib/applications';
import {columns,moveApplication,type Column} from '@/lib/kanban';
import {candidateApplication,type Selection} from '@/lib/search-types';
import {kstDate} from '@/lib/jobs';
import {Editor} from './editor';
import {Calendar} from './calendar';
import {JobCard} from './kanban';
import {SearchDialog} from './search-dialog';
export default function Home(){
 const [state,setState]=useState<State|null>(null),[canEdit,setCanEdit]=useState(true),[tab,setTab]=useState('calendar'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Application|null>(null),[selection,setSelection]=useState<Selection|null>(null),[focus,setFocus]=useState<string>(),[focusLabel,setFocusLabel]=useState<string>(),[adding,setAdding]=useState(false),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[sort,setSort]=useState('deadline'),[now,setNow]=useState(Date.now());
 async function load(){try{const r=await fetch('/api/state',{cache:'no-store'}),s=JSON.parse(await r.text());if(!r.ok)throw new Error(s.error);setState(s);setCanEdit(true);const access=await fetch('/api/access',{cache:'no-store'});if(access.ok){const a=await access.json() as {canEdit?:boolean};setCanEdit(a.canEdit!==false)}setError('')}catch(e){setError(e instanceof Error?e.message:'데이터를 불러오지 못했습니다.')}}
 useEffect(()=>{void load();const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{document.title=tab==='calendar'?'캘린더 | 취준캘린더':tab==='all'?'내 공고 | 취준캘린더':'대시보드 | 취준캘린더'},[tab]);
 async function mutate(body:Record<string,unknown>,optimistic?:Application){if(!state||busy)throw new Error('잠시 후 다시 시도해주세요.');const before=state;let refreshed=false;setBusy(true);setError('');if(optimistic)setState({...before,applications:before.applications.map(a=>a.id===optimistic.id?optimistic:a)});try{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,revision:before.revision})}),s=JSON.parse(await r.text());if(!r.ok){if(optimistic)setState(before);if(r.status===409){await load();refreshed=true;}throw new Error(s.error)}setState(s);setNotice('변경 사항을 저장했습니다.')}catch(e){if(optimistic&&!refreshed)setState(before);throw e}finally{setBusy(false)}}
 const apps=state?.applications??[],events=calendarEvents(apps),upcoming=events.filter(e=>!['recruitment_start','result_confirmed'].includes(e.type)&&isUpcoming(e,now));
 const filtered=apps.filter(a=>(!query||(a.companyName+' '+a.postingTitle+' '+a.role).toLowerCase().includes(query.toLowerCase()))&&(!status||a.managementStatus===status)).sort((a,b)=>sort==='updated'?b.updatedAt.localeCompare(a.updatedAt):(a.recruitment.end?.date??'9999').localeCompare(b.recruitment.end?.date??'9999')||(a.recruitment.end?.time??'').localeCompare(b.recruitment.end?.time??''));
 function open(a:Application,focusId?:string,focusText?:string){setSelection(null);setEditing(a);setFocus(focusId);setFocusLabel(focusText)}
 function openEvent(e:CalendarEvent){const a=apps.find(a=>a.id===e.applicationId);if(a){const point=e.schedule.start??e.schedule.end;open(a,e.stageId??e.personalId??'recruitment',`${eventLabels[e.type]} · ${point?.date??'날짜 미공개'}${point?.time?` ${point.time}`:''}`)}}
 async function move(a:Application,c:Column){if(c.kind==='archived'){open(a,'application-status');return}if(c.kind==='accepted'&&!confirm(a.companyName+' 공고를 최종합격으로 변경할까요?'))return;try{const changed=moveApplication(a,c);await mutate({action:'save',application:changed},changed)}catch(e){setError(e instanceof Error?e.message:'이동을 저장하지 못해 이전 상태로 돌아왔습니다.')}}
 async function moveEvent(e:CalendarEvent,targetDate:string){const a=apps.find(x=>x.id===e.applicationId);if(!a)return;try{const changed=moveCalendarEvent(a,e,targetDate);if(JSON.stringify(changed)===JSON.stringify(a))return;await mutate({action:'save',application:changed},changed)}catch(err){setError(err instanceof Error?err.message:'일정 이동을 저장하지 못해 이전 상태로 돌아왔습니다.')}}
 return <main className="workspace"><header><a href="/" className="brand" aria-label="취준캘린더 홈"><span className="brand-mark" aria-hidden="true"><svg viewBox="0 0 24 24" focusable="false"><rect x="3" y="4.5" width="18" height="16" rx="3"/><path d="M7 3v4M17 3v4M3 9.5h18M7 13h3M14 13h3M7 17h3"/></svg></span><strong>취준캘린더</strong></a><nav aria-label="주 메뉴">{[['calendar','캘린더'],['all','내 공고'],['dashboard','대시보드']].map(([v,l])=><button key={v} aria-current={tab===v?'page':undefined} className={tab===v?'active':''} onClick={()=>setTab(v)}>{l}</button>)}</nav><button className="primary add-button" disabled={!state||busy} onClick={()=>setAdding(true)}>＋ 내 공고 추가</button></header>
 <div className="workspace-content"><div className="page-heading"><div><h1>{tab==='calendar'?'캘린더':tab==='all'?'내 공고':'대시보드'}</h1><p>{tab==='calendar'?'날짜별 마감과 전형 일정을 한눈에 확인하세요.':tab==='all'?'저장한 공고를 검색하고 진행 상황을 관리하세요.':'전체 지원 현황을 간단히 확인하세요.'}</p></div><div className="heading-meta"><span>{kstDate(now)} · KST</span><span className="badge">개인 작업공간 · 로그인 없이 사용</span><a href="/api/export">백업 ↓</a></div></div>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>void load()}>다시 불러오기</button></div>}{notice&&<div className="toast" role="status">{notice}</div>}
 {!state?<div className="loading-board" aria-label="공고 불러오는 중">{[1,2,3,4].map(i=><div className="skeleton" key={i}/>)}</div>:tab==='calendar'?<Calendar events={events} undatedApplications={apps.filter(a=>!calendarEvents([a]).length)} onOpen={openEvent} onOpenApplication={a=>open(a)} onMove={moveEvent} canEdit={canEdit} busy={busy}/>:<>
 {tab==='dashboard'&&<><section className="stats-strip">{[['전체 공고',apps.length],['지원 중',apps.filter(a=>a.managementStatus==='active').length],['3일 이내 마감',apps.filter(a=>due(a,now).urgent).length],['최종합격',apps.filter(a=>a.managementStatus==='accepted').length]].map(([label,count])=><div key={label}><span>{label}</span><strong>{count}</strong></div>)}</section>{upcoming.length>0&&<section className="next-strip"><h2>다가오는 일정</h2>{upcoming.slice(0,4).map(e=><button key={e.id} onClick={()=>openEvent(e)}><time>{eventDate(e).slice(5)} <small>{(e.schedule.start??e.schedule.end)?.time??'시각 미공개'}</small></time><span><strong>{e.companyName}</strong><small>{e.title}</small></span></button>)}<button className="calendar-shortcut" onClick={()=>setTab('calendar')}>전체 보기 ↗</button></section>}</>}
 <div className="board-toolbar"><label className="board-search"><span aria-hidden="true">⌕</span><input aria-label="내 공고 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="기업명, 공고명 검색"/></label><div><select aria-label="지원 상태 필터" value={status} onChange={e=>setStatus(e.target.value)}><option value="">모든 상태</option>{Object.entries(managementLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="공고 정렬" value={sort} onChange={e=>setSort(e.target.value)}><option value="deadline">마감 임박순</option><option value="updated">최근 수정순</option></select></div></div>
 {!apps.length?<div className="empty welcome"><div className="welcome-icon">＋</div><h2>다음 기회를 이곳에 모아보세요</h2><p>실제 채용공고를 검색하거나 직접 등록하고,<br/>전형과 일정을 한곳에서 관리하세요.</p>{canEdit&&<button className="primary" onClick={()=>setAdding(true)}>첫 공고 추가하기</button>}</div>:<div className="application-grid">{filtered.map(a=><JobCard key={a.id} application={a} next={upcoming.find(e=>e.applicationId===a.id)} now={now} onOpen={()=>open(a)} onMove={c=>void move(a,c)} canEdit={canEdit} busy={busy} allColumns={columns(apps)}/>)}</div>}
 {apps.length>0&&!filtered.length&&<p className="empty">조건에 맞는 공고가 없습니다.</p>}{tab==='dashboard'&&apps.length>0&&<p className="board-hint">공고를 열면 현재 전형과 다음 일정을 자세히 관리할 수 있습니다.</p>}</>}
 <footer>취준캘린더 · 모집 마감과 지원 진행은 별도로 관리합니다. 모든 일정은 한국시간입니다.</footer></div>
 {adding&&<SearchDialog onClose={()=>setAdding(false)} onManual={()=>{setAdding(false);setSelection(null);setEditing(newApplication());setFocus(undefined);setFocusLabel(undefined)}} onSelect={(candidate,selected)=>{setAdding(false);setSelection(selected);setEditing(candidateApplication(candidate));setFocus(undefined);setFocusLabel(undefined)}}/>}
 {editing&&<Editor key={editing.id} application={editing} readOnly={!canEdit} isNew={!apps.some(a=>a.id===editing.id)} focusId={focus} focusLabel={focusLabel} onClose={()=>{setEditing(null);setSelection(null);setFocusLabel(undefined)}} onSave={async(application,allowDuplicate)=>{await mutate({action:selection?'save-selected':'save',application,allowDuplicate,...(selection?{selection}:{})});setEditing(null);setSelection(null);setFocusLabel(undefined)}} onDelete={async()=>{await mutate({action:'delete',id:editing.id});setEditing(null)}}/>}
 </main>
}


