"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { deadline,formatPoint,pointMs,type Posting,type Store,type Provider } from "@/lib/jobs";
type SearchResult={provider:Provider;company:string;postings:Posting[];warning?:string};
const checked=(iso:string)=>new Intl.DateTimeFormat("ko-KR",{month:"long",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Seoul"}).format(new Date(iso));

export default function Home(){
 const [store,setStore]=useState<Store|null>(null),[modal,setModal]=useState(false),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const r=await fetch("/api/state",{cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b.error);setStore(b)},[]);
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[load]);
 const mutate=useCallback(async(payload:Record<string,unknown>)=>{const r=await fetch("/api/state",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),b=await r.json();if(!r.ok)throw new Error(b.error);setStore(b)},[]);
 const posts=useMemo(()=>[...(store?.postings??[])].sort((a,b)=>a.end&&b.end?pointMs(a.end)-pointMs(b.end):0),[store]);
 const company=new Map(store?.companies.map(c=>[c.id,c.name])??[]);
 return <main className="app-shell"><header><a className="brand" href="#top"><span>J</span><strong>JOBTIME</strong></a><button className="primary" onClick={()=>setModal(true)}>＋ 내 공고 추가</button></header>
  <section className="intro" id="top"><div><p className="eyebrow">MY APPLICATION, MY TIMELINE</p><h1>지금 필요한 공고만,<br/><em>마감까지 한눈에.</em></h1><p>기업명이나 공식 공고 주소로 찾고, 내가 지원할 공고 하나만 골라 관리하세요.</p></div><div className="orb"><span>{posts.filter(p=>!deadline(p).closed).length}</span><small>진행 중인<br/>나의 공고</small></div></section>
  {message&&<div className="notice"><span>{message}</span><button onClick={()=>setMessage("")}>×</button></div>}
  <section className="list"><div className="list-title"><div><p className="eyebrow">MY BOARD</p><h2>나의 지원 공고</h2></div><span>{posts.length}개의 타임라인</span></div>
  {!store?<div className="empty">나의 공고를 불러오는 중이에요.</div>:posts.length?posts.map((p,i)=><JobCard key={p.id} post={p} company={company.get(p.companyId)??"기업"} index={i} update={(patch)=>mutate({action:"update-posting",id:p.id,...patch}).catch(e=>setMessage(e.message))} remove={()=>mutate({action:"remove-posting",id:p.id}).catch(e=>setMessage(e.message))}/>):<div className="empty"><div className="empty-icon">⌁</div><strong>아직 고른 공고가 없어요</strong><p>기업명이나 공식 공고 주소로 검색한 뒤<br/>내가 지원할 공고를 하나 골라보세요.</p><button className="primary" onClick={()=>setModal(true)}>첫 공고 추가하기</button></div>}</section>
  <footer><span>일정은 한국시간 기준이에요.</span><span>지원 전 공식 원문을 한 번 더 확인해 주세요.</span></footer>
  {modal&&<AddPosting close={()=>setModal(false)} added={async(result,post)=>{await mutate({action:"add-selected",provider:result.provider,posting:post});setModal(false);setMessage("나의 지원 공고에 추가했어요.")}}/>}
 </main>
}

function JobCard({post,company,index,update,remove}:{post:Posting;company:string;index:number;update:(p:Record<string,unknown>)=>void;remove:()=>void}){const d=deadline(post);return <article className={`job ${d.closed?"closed":""}`}><div className="job-index">{String(index+1).padStart(2,"0")}</div><div className="job-main"><div className="company-line"><span className="company-dot"/>{company}<span className={`badge ${d.tone}`}>{d.closed?"마감":d.label}</span></div><h3>{post.title}</h3><div className="timeline"><div><small>모집 시작</small><strong>{formatPoint(post.start)}</strong></div><span className="line"/><div><small>모집 마감</small><strong>{formatPoint(post.end)}</strong></div></div><div className="job-actions"><label>지원 상태<select value={post.stage} onChange={e=>update({stage:e.target.value})}><option>관심</option><option>지원 준비</option><option>지원 완료</option></select></label><a href={post.url} target="_blank" rel="noreferrer">공식 공고 보기 ↗</a></div><details><summary>메모와 공고 정보</summary><textarea defaultValue={post.notes} placeholder="준비할 서류나 자소서 아이디어를 적어두세요." onBlur={e=>{if(e.target.value!==post.notes)update({notes:e.target.value})}}/><p>{post.evidence}</p><p>{checked(post.checkedAt)}에 공식 사이트에서 확인</p><button className="remove" onClick={remove}>이 공고 삭제</button></details></div></article>}

function AddPosting({close,added}:{close:()=>void;added:(r:SearchResult,p:Posting)=>Promise<void>}){const [query,setQuery]=useState(""),[result,setResult]=useState<SearchResult|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");async function search(e:React.FormEvent){e.preventDefault();setLoading(true);setError("");try{const r=await fetch("/api/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query})}),b=await r.json();if(!r.ok)throw new Error(b.error);setResult(b)}catch(v){setError(v instanceof Error?v.message:"검색하지 못했습니다.")}finally{setLoading(false)}}return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={close}>×</button>{!result?<form onSubmit={search}><p className="eyebrow">FIND MY POSTING</p><h2>어떤 공고를 준비하나요?</h2><p>기업명 또는 공식 채용 공고 주소를 입력해 주세요.</p><label>기업명 · 공고 주소<input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="예: 국민은행 또는 https://…" required/></label><div className="support">현재 국민은행 · 기업은행 · 농협은행을 지원해요.</div>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={loading}>{loading?"공식 공고 찾는 중…":"공고 검색"}</button></form>:<div><p className="eyebrow">CHOOSE ONE</p><h2>{result.company}에서<br/>어떤 공고를 준비하나요?</h2><p className="result-guide">아래에서 나의 지원 공고 하나를 선택해 주세요.</p>{result.warning&&<p className="support">{result.warning}</p>}<div className="choices">{result.postings.map(p=><button key={p.id} className="choice" onClick={()=>added(result,p).catch(v=>setError(v.message))}><span><b>{p.title}</b><small>{formatPoint(p.end)} 마감</small></span><i>선택 →</i></button>)}</div>{!result.postings.length&&<p className="support">현재 선택할 수 있는 공고가 없습니다.</p>}{error&&<p className="form-error">{error}</p>}<button className="back" onClick={()=>setResult(null)}>← 다시 검색</button></div>}</div></div>}
