"use client";
import {useMemo,useState} from "react";
import {emptyRange,type Application,type Point} from "@/lib/applications";
import {Modal} from "./editor";

type ScheduleDialogProps={date:string;applications:Application[];onClose:()=>void;onSave:(application:Application)=>Promise<void>};

export function ScheduleDialog({date,applications,onClose,onSave}:ScheduleDialogProps){
 const [applicationId,setApplicationId]=useState(applications[0]?.id??""),[kind,setKind]=useState("preparation"),[title,setTitle]=useState(""),[day,setDay]=useState(date),[time,setTime]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const application=applications.find(a=>a.id===applicationId),availableStages=useMemo(()=>application?.stages.filter(s=>s.applicable&&!(s.schedule.start||s.schedule.end))??[],[application]);
 async function save(e:React.FormEvent){e.preventDefault();if(!application||!day){setError("공고와 날짜를 확인해주세요.");return}if(['personal','preparation'].includes(kind)&&!title.trim()){setError("일정명을 입력해주세요.");return}if(!['personal','preparation'].includes(kind)&&!availableStages.some(s=>s.id===kind)){setError("전형을 다시 선택해주세요.");return}setBusy(true);setError("");const point:Point={date:day,time:time||null,timezone:"Asia/Seoul"};const next=structuredClone(application);if(kind==="personal")next.personalEvents.push({id:crypto.randomUUID(),title:title.trim(),schedule:{...emptyRange(),start:point},notes:""});else if(kind==="preparation")next.preparationItems=[...(next.preparationItems??[]),{id:crypto.randomUUID(),title:title.trim(),date:point,showOnCalendar:true,completedAt:null,createdAt:new Date().toISOString()}];else{const stage=next.stages.find(s=>s.id===kind);if(!stage){setError("전형을 찾지 못했습니다.");setBusy(false);return}stage.schedule={...stage.schedule,start:point,tentative:false}}try{await onSave(next);onClose()}catch(e){setError(e instanceof Error?e.message:"일정을 저장하지 못했습니다. 입력 내용은 유지됩니다.")}finally{setBusy(false)}}
 return <Modal title="일정 추가" onClose={()=>{if(!busy)onClose()}} className="schedule-dialog"><form onSubmit={save}><p className="hint">선택한 날짜에 공고 일정이나 체크할 준비 항목을 추가합니다.</p>{!applications.length?<p className="empty">먼저 공고를 추가해주세요.</p>:<><label>연결할 공고<select value={applicationId} onChange={e=>{setApplicationId(e.target.value);setKind("preparation")}} disabled={busy}>{applications.map(a=><option key={a.id} value={a.id}>{a.companyName} · {a.postingTitle}</option>)}</select></label><label>일정 종류<select value={kind} onChange={e=>{setKind(e.target.value);if(!['personal','preparation'].includes(e.target.value))setTitle(availableStages.find(s=>s.id===e.target.value)?.name??"")}} disabled={busy}><option value="preparation">개인 준비 항목</option><option value="personal">개인 일정</option>{availableStages.map(s=><option key={s.id} value={s.id}>{s.name} 일정</option>)}</select></label>{['personal','preparation'].includes(kind)&&<label>일정명<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="예: 자기소개서 최종 점검" disabled={busy}/></label>}<div className="schedule-date-grid"><label>날짜<input required type="date" value={day} onChange={e=>setDay(e.target.value)} disabled={busy}/></label><label>시각 (선택)<input type="time" value={time} onChange={e=>setTime(e.target.value)} disabled={busy}/></label></div></>} {error&&<p role="alert" className="error">{error}</p>}<div className="save-bar"><button className="primary" disabled={busy||!applications.length}>{busy?"저장 중…":"일정 저장"}</button><button type="button" disabled={busy} onClick={onClose}>취소</button></div></form></Modal>
}
